### ISSUE TITLE
Eliva returns too many items.

### ISSUE THREAD

**Issue by AlfHou** [ottopaulsen/node-red-contrib-power-saver#101]
Recently I got a new error when using the `eliva-add-tariff` node. They seem to return too few values compared to the expected 48.

![image](https://user-images.githubusercontent.com/20001253/195691256-abb1f663-9841-431c-a770-797884ec59ac.png)

**Comment by ottopaulsen** [comment]
Kan det ha vært at Elvia manglet data?
Hvordan er det nå?

**Comment by marhoy** [comment]
I think the Elvia API has been a bit unstable, here's some entries from my log:

```
13 Oct 19:49:36 - [warn] [http request:Elvia API] JSON parse error
14 Oct 08:02:00 - [error] [http request:Elvia API] no response from server
```

**Comment by AlfHou** [comment]
Hi! Looks to be working fine again. Likely some instability with the Elvia API as @marhoy mentioned :)
