### ISSUE TITLE
Error: Invalid context key

### ISSUE THREAD

**Issue by Csstenersen** [ottopaulsen/node-red-contrib-power-saver#107]
i'm trying to send input from node-red-nordpool-api to powersaver. 
seem like it works fine into "Price Receiver" but fails with _Error: Invalid context key_ in Best Save node.
Please se attached json.txt with data from price receiver to best save node
[json.txt](https://github.com/ottopaulsen/node-red-contrib-power-saver/files/9881050/json.txt)

what is wrong with the context?

**Comment by ottopaulsen** [comment]
There is obviously something wrong with the format of the data in your json file.
The "start" values are numbers, but shall be strings.
See [Strategy input format](https://powersaver.no/nodes/strategy-input.html) for the correct format.
Is your json output from Price Receiver?
If so, please show me the data sent in to the Price Receiver.

**Comment by Csstenersen** [comment]
got it to work when using .toISOString() on my time format. 
this flow is now a success:
![image](https://user-images.githubusercontent.com/48843914/198384914-a581246d-e3d7-4d8c-a26b-56189f379db3.png)

**Comment by choel83** [comment]
I'm having the same error "Invalid context key". 
I can't figure out what the cause is. Date is in iso format, value is a number. 
Attached the output of Price Receiver. 

Best regards,
Joel
[Output PriceReciever.txt](https://github.com/ottopaulsen/node-red-contrib-power-saver/files/10912489/Output.PriceReciever.txt)

**Comment by ottopaulsen** [comment]
@choel83 You have a slightly different date format then what is specified. I am not 100% sure that is the reason, but it may be. See https://powersaver.no/nodes/strategy-input.html for an example of the correct format.

**Comment by choel83** [comment]
Thanks, missed that small difference. Changing it did the trick.
