### ISSUE TITLE
Details of the json behind "Get live data" for non-tibber users

### ISSUE THREAD

**Issue by shadowano** [ottopaulsen/node-red-contrib-power-saver#111]
I was looking at https://powersaver.no/examples/example-grid-tariff-capacity-part.html#get-live-data, and since I don't have tibber but my own AMS reader I need to make sure I send the correct json data. 

"power": This is current power in W?
"accumulatedConsumption": Is this accumulated kWh for current day?
"accumulatedConsumptionLastHour": Is this accumulated kWh for current hour?

Thanks in advance:)

**Comment by ottopaulsen** [comment]
Yes, your assumptions are correct.

**Comment by shadowano** [comment]
Thanks, I'll close this
