### ISSUE TITLE
Norde Red Crash

### ISSUE THREAD

**Issue by kimstor1435** [ottopaulsen/node-red-contrib-power-saver#113]
Hi

Sometimes my node red crash, seems to be related to the capacity nodes.

![image](https://user-images.githubusercontent.com/61433087/201904993-eee3fe6f-ba41-43d7-b73a-5c7038346752.png)

**Comment by ottopaulsen** [comment]
Can it be that you are losing connection to HA? 
The first two lines may indicate that.
I think it has to do with HA or the HA node for updating the sensor, and not with the capacity nodes.

**Comment by kimstor1435** [comment]
You are right, I recreated the issue when I rebooted HA.
I will close the issue now.
