### ISSUE TITLE
Lowest price "No Schedule" problem 

### ISSUE THREAD

**Issue by rsuten** [ottopaulsen/node-red-contrib-power-saver#114]
Hello
Thank you Otto for creating all the powersaver nodes

I have a small problem with the lowest price node throwing "no schedule". Can someone help me with that please? 

Today i had it working in the moring. It started as **"true" at 00:00** , and **"false" at  07:00 AM** (Worked perfectly). Then the problem starts at **19:00** when it suddenly sends _**"no schedule"**_ and both True and False outputs get respectively activated at same time. It was scheduled as "**True" at 19:00** but had false instead as output. What can be the cause of "no schedule" and incorrect output? 

I suspect the time input with pricedata is the issue. I have not figured out how to change time and timezone from Zulu to +02:00 UTC. 
I can't fix it by using tibber node or home assistant nordpool sensor.

If someone have suggestions for a fix i would greatly appreciate

Look at the png's for info about configuration

![image](https://user-images.githubusercontent.com/118310809/202024960-383a4786-55c3-441b-9c70-ea116e0ad761.png)
![image](https://user-images.githubusercontent.com/118310809/202025039-f1f88ae4-78aa-4561-9bc8-3aa1d2c8f65e.png)

**Comment by shadowano** [comment]
It looks like you are missing a node between nordpool and strategy node. See the following pages for more information.

https://powersaver.no/nodes/strategy-input.html
https://powersaver.no/nodes/ps-receive-price.html

**Comment by rsuten** [comment]
I changed the jsonata strategy input alittle so i will see if it works tomorrow.
I don't have tibber or homeassistant, so the recive price node would not make a difference. I could get tibber as a solution, but i try to subscribe to as few services as possible

**Comment by ottopaulsen** [comment]
Make sure you have prices until the end of day. Looks like you are missing one hour, maybe because you are using UTC time. The node must have all hours to be able to calculate, since the period is 00-00.

**Comment by ottopaulsen** [comment]
Have you solved this? If so, please close the issue.
