### ISSUE TITLE
How does "Capacity part of grid tariff"-nodes and strategy-nodes work together?

### ISSUE THREAD

**Issue by shadowano** [ottopaulsen/node-red-contrib-power-saver#117]
Hi,

In order to save money in Norway we need to move power to cheaper hours, but also keep the amount of kwh used per hour to a low level. This mean we need to run two flows, one using the strategy nodes and a different one implementing "[Capacity part of grid tariff](https://powersaver.no/examples/example-grid-tariff-capacity-part.html)".

If the strategy nodes schedules ON for the next three hours, but the Reduction-node sends OFF (because current hour will exceed e.g. 5 kwh), can the strategy nodes override this by sending a new ON message during a high kWh hour? When does a strategy node send a new output (unless restart of HA/node-red or injected manually)? 

Is it recommended to somehow join these two flows, so that when Reduction-node sends OFF, there is never something else sending ON to a device?

**Comment by ottopaulsen** [comment]
I have an idea that the capacity part shall be able to turn off switches controlled by strategy nodes by using the new override function, but I have not got the time to implement the feature in the capacity part yet. Feel free to try yourself :-)

**Comment by shadowano** [comment]
The override function in [Dynamic config](https://powersaver.no/nodes/ps-strategy-best-save.html#dynamic-config)? So If I override with OFF, do I override again when the next hour starts by sending AUTO? I can't find documentation of what AUTO really is.

**Comment by ottopaulsen** [comment]
Auto means going back to whatever the node has planned. You must send auto to quit override.

**Comment by shadowano** [comment]
Thanks for updating the documentation! I see you send actions to the strategy nodes, but strategy nodes needs price information. Do I just connect both price receiver node and reduction/reset actions nodes to the strategy nodes' input?

**Comment by ottopaulsen** [comment]
Yes, the nodes aaccept different types of input.

**Comment by shadowano** [comment]
One more question, I see in your example flow in powersaver.no that you connect the reduction and reset actions nodes to a call service node. Won't the strategy nodes pass on the override values and turn off the services? Or will it only avoid the strategy nodes to send any updates out?

**Comment by ottopaulsen** [comment]
There are two types of actions, you can [read about them here](https://powersaver.no/examples/example-grid-tariff-capacity-part.html#reduction-actions).

The `Call service actions` need the cal service node, while the `Override Power Saver actions` need to go to the Power Saver nodes. If you only use one of them, you can skip the other, but you can use both type of actions at the same time.

**Comment by shadowano** [comment]
Thanks you so you much for the help:)
