### ISSUE TITLE
Reduction Action triggers on every hour

### ISSUE THREAD

**Issue by shadowano** [ottopaulsen/node-red-contrib-power-saver#121]
Every hour I see that the reduction action function node is shutting down my heat box on the hour, every hour. I set this up yesterday to control my water heater.

What I see is that the hour estimate can have some wild numbers from very low negative values to very high positive numbers the first 3 minutes. The node "Collect estimate for hour" has a value of 3 in ESTIMATION_TIME_MINUTES variable. Before the buffer is filled up to get a correct hour estimate, the numbers are not close to what is should be. 

![image](https://user-images.githubusercontent.com/3582807/204112400-67b2efb9-562e-43cb-8712-b69833d98d6a.png)

I would expect two things to happen:

1. The estimation doesn't go wild, but uses the average of the values collected so far.
2. The reduction trigger doesn't fire at least until ESTIMATION_TIME_MINUTES has passed.

Solving one of them will solve the problem. 

![image](https://user-images.githubusercontent.com/3582807/204112252-4b472716-56c1-4725-b019-02a7ad72c6bf.png)

**Comment by gulli1986** [comment]
I also experience the same, The first few minutes past every hours, some of my reduction actions are triggered which I don't think is actually necessary.

It would be good to give the system time to adjust, let's say the first 5 minutes past the hour, before any reduction actions is taken.

**Comment by shadowano** [comment]
@gulli1986 I see that @ottopaulsen has updated the [reduction action code](https://powersaver.no/examples/example-grid-tariff-capacity-part.html#reduction-actions) on powersaver.no with a configure constant for number of minutes before it takes action. 

Thanks @ottopaulsen, I'll close this as solved then:)
