### ISSUE TITLE
Reset Action node sets actionTaken to false

### ISSUE THREAD

**Issue by shadowano** [ottopaulsen/node-red-contrib-power-saver#122]
In line 27 and 28 of the [Reset Action node](https://powersaver.no/examples/example-grid-tariff-capacity-part.html#reset-actions) on powersaver.no I see the actionTaken is set to false, and savedConsumption is set to 0. Is this a bug?

**Comment by ottopaulsen** [comment]
No.
When the action is reset, it is no longer taken, and does not save anything.
