### ISSUE TITLE
Capacity grid alarm / increase possible bugs?

### ISSUE THREAD

**Issue by gulli1986** [ottopaulsen/node-red-contrib-power-saver#126]
Hello,

It looked like something happened yesterday after Tibber went down (Tibber is now working again). The system often goes to `Capacity Status = "Alarm"`, `Capacity Alarm Level = 8` and show `Capacity Increase Possible = 0` even though I still have plenty of kW I could use before hitting the limit, see example below:

![image](https://user-images.githubusercontent.com/84970544/204613734-f20a724f-cc9c-4330-aec7-834a1397cc34.png)

I am in step 10 kWh. The `Capacity Hour Estimate = 5.25` in this example so I still have plenty of time before I go over 10 kWh. Shouldn't be any alarm here....

I also tried updated to the "new" capacity grid example after the latest powersaver update, still having the same issue.

The issue comes and goes during the day, is that coming from Tibber and are you experiencing the same issue?

**Comment by ottopaulsen** [comment]
Jeg foreslår at du setter på debug-noder og ser hva som kommer ut av de forskjellige nodene, og ser hva som virker mistenkelig.

**Comment by gulli1986** [comment]
Da har jeg prøvd det. Jeg må si at alt ser fint ut på debug-nodene, allikevel så får jeg feil alarm.

Denne kommer ut av `Find highest per day` noden:

```
11/30/2022, 8:42:02 PMnode: find highest
msg : Object
object
payload: object
highestPerDay: array[30]
highestCounting: array[3]
0: object
from: "2022-11-27T05:00:00.000+01:00"
consumption: 11.25
1: object
from: "2022-11-07T02:00:00.000+01:00"
consumption: 8.89
2: object
from: "2022-11-12T13:00:00.000+01:00"
consumption: 8.844
highestToday: object
from: "2022-11-30T18:00:00.000+01:00"
consumption: 6.75
currentMonthlyMaxAverage: 9.661333333333333
_msgid: "e69a33cd91f26180"
```

Denne kommer ut av `Collect estimate for hour` noden:

```
11/30/2022, 8:42:13 PMnode: collect estimate
msg : Object
object
payload: object
accumulatedConsumption: 86.934158
accumulatedConsumptionLastHour: 5.374158
periodMs: 10000
consumptionInPeriod: 0.018215999999995347
averageConsumptionNow: 6.557759999998324
timeLeftMs: 1070000
consumptionLeft: 1.9491119999995021
hourEstimate: 7.323269999999503
currentHour: "2022-11-30T19:00:00.000Z"
_msgid: "ef09f6d79ae26ddf"
```

Dette går inn i `Calcuate value` noden og dette kommer ut:

```
11/30/2022, 8:42:13 PMnode: calculate values
msg : Object
object
payload: object
status: "Alarm"
statusOk: false
statusWarning: false
statusAlarm: true
alarmLevel: 8
highestPerDay: array[30]
highestCounting: array[3]
0: object
from: "2022-11-27T05:00:00.000+01:00"
consumption: 11.25
1: object
from: "2022-11-07T02:00:00.000+01:00"
consumption: 8.89
2: object
from: "2022-11-12T13:00:00.000+01:00"
consumption: 8.844
highestCountingWithCurrent: array[3]
0: object
from: "2022-11-27T05:00:00.000+01:00"
consumption: 11.25
1: object
from: "2022-11-07T02:00:00.000+01:00"
consumption: 8.89
2: object
from: "2022-11-12T13:00:00.000+01:00"
consumption: 8.844
highestToday: object
from: "2022-11-30T18:00:00.000+01:00"
consumption: 6.75
highestTodayConsumption: 6.75
highestTodayFrom: "2022-11-30T18:00:00.000+01:00"
currentMonthlyEstimate: 9.661
accumulatedConsumptionLastHour: 5.374
consumptionLeft: 1.949
hourEstimate: 7.323
averageConsumptionNow: 6.558
reductionRequired: 0
reductionRecommended: 0
increasePossible: 0
currentStep: 10
currentHourRanking: 4
timeLeftSec: 1070
periodMs: 10000
accumulatedConsumption: 86.934158
_msgid: "ef09f6d79ae26ddf"

```

Jeg skjønner ikke hvorfor `status=arlarm`, `alarm level = 8` og `increasePossible=0`.
`hourEstimate=7.323`, `currentStep=10`

**Comment by gulli1986** [comment]
Lukker denne. Ser ut til å fungerer igjen etter at jeg oppdaterte til siste versjon.
