### ISSUE TITLE
NaN as setpoint when price is missing for the day after

### ISSUE THREAD

**Issue by zyberzero** [ottopaulsen/node-red-contrib-power-saver#131]
I've imported the flow for heat-capacitor and adapted it to my house, `time+1C` is  `480` and `time-1C` is set to `360`.

I'm using Tibber as the price source, and I am in SE3.

It works fine as long as I have price info for the next day, but when the list of trades ends on day 2 at around `07:00` - and  no price info is available for day 3 -  it sets the setpoint to NaN which the rest of the system interprets as `0.0` 🥶 

I'd expect it to set the setpoint to "sell" mode.

I am probably doing something wrong, and  need enlightenment but I think that I've followed the instructions. 

This happened for example today, with the output from the heat-capacitor node can [be found here](https://gist.github.com/zyberzero/99a579624abfa19d41de57a98625d85d)

**Comment by TomTorger** [comment]
Ouch... Sorry ❄️ Sounds like a serious bug. I will make a test and try to re-create it :-)

**Comment by TomTorger** [comment]
I changed the way the current values are fetched, and the current PR should fix this issue :-)

**Comment by zyberzero** [comment]
Awesome, thanks for looking into it! I'll test it as soon it is released :)

**Comment by zyberzero** [comment]
I tested the v4.1.4 and it seems to work now. Thank you!
