### ISSUE TITLE
Capacity grid - to include dynamic charging?

### ISSUE THREAD

**Issue by gulli1986** [ottopaulsen/node-red-contrib-power-saver#136]
Hello,
I have been working to incorporate the capacity grid example together with dynamic charging from my Easee charger controlling the Amps.

I have tested several solutions but making both the capacity grid example and charging work together have proved difficult. Is there any way dynamic charging (controlling the charger amps up and down) will be incorporated to the capacity grid at some point?

Thanks

**Comment by ottopaulsen** [comment]
Since this is a standard function node, you can do whatever you like, including adding more outputs.

**Comment by gulli1986** [comment]
OK, thanks I will dig more into it. Closing this post for now.
