### ISSUE TITLE
Simulate override

### ISSUE THREAD

**Issue by haavardNO** [ottopaulsen/node-red-contrib-power-saver#140]
I am trying to test the ovveride function of the strategy nodes to verify that my logic is working.
Just injecting off and auto does not work. Is there a way to do this?

![image](https://user-images.githubusercontent.com/27728530/209948633-25ff41cb-4556-40f7-bec4-81617bc935f0.png)

**Comment by ottopaulsen** [comment]
You must use JSON:
<img width="482" alt="image" src="https://user-images.githubusercontent.com/3034647/210011632-4fade8b4-3537-4abc-bffb-ac8f1e52e749.png">

**Comment by haavardNO** [comment]
Thanks :)
That solved it.
