### ISSUE TITLE
Unable to get live data from tibber

### ISSUE THREAD

**Issue by haavardNO** [ottopaulsen/node-red-contrib-power-saver#149]
My live data node is no longer able to connect it seams. Anyone who has experienced the same?
It is stuck at connecting. 
![image](https://user-images.githubusercontent.com/27728530/212836026-868cab94-88e9-4377-911d-6cdb375910a4.png)

**Comment by ottopaulsen** [comment]
Have you updated the Tibber nodes lately? They have changed.

**Comment by haavardNO** [comment]
Thanks @ottopaulsen , that solved it.
I changed from installing the tibber implementation from the HA UI to the node red UI. Then it was updated...
