### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by Swoop86** [ottopaulsen/node-red-contrib-power-saver#15]
Tried both chrome and safari, both only show blank pages. (changelog seems to work fine though).

<img width="1270" alt="Skjermbilde 2021-12-15 kl  21 38 27" src="https://user-images.githubusercontent.com/5503114/146261559-06442c8f-d687-4ae0-bd24-055fc511d36b.png">
<img width="1270" alt="Skjermbilde 2021-12-15 kl  21 38 20" src="https://user-images.githubusercontent.com/5503114/146261567-e980bd9b-a7b4-40c5-9ba7-826730b5415b.png">
<img width="1270" alt="Skjermbilde 2021-12-15 kl  21 38 14" src="https://user-images.githubusercontent.com/5503114/146261571-33a78307-f479-49e7-85d9-e01d92cd97a1.png">
<img width="1270" alt="Skjermbilde 2021-12-15 kl  21 38 08" src="https://user-images.githubusercontent.com/5503114/146261573-d68e1e36-d4ec-46b2-8d2e-fd48259365f8.png">

**Comment by warfair1337** [comment]
Experiencing the same thing here (Safari and Edge Chromium).

**Comment by ottopaulsen** [comment]
Thanks for letting me know.
This should be fixed now.

I was wondering, did it work before, do you know?

**Comment by warfair1337** [comment]
For me it worked fine the day before :)

**Comment by Swoop86** [comment]
Can't remember if it was that specific layout, but there was something similar :)
