### ISSUE TITLE
Wrong time format (24h vs 12h)

### ISSUE THREAD

**Issue by osaether** [ottopaulsen/node-red-contrib-power-saver#151]
On my system, Power Saver is displaying the time in 12h format while I expect 24H format. I am running HA in a VM in ProxMox. I have tried:

 * Set the locale of proxmox to en_GB which uses 24h format.
 * Set the browser default language to en_GB
 * Set the Windows 11 language to en_GB
 * Set the time format in Windows to 24h.

I have a suspicion that node-red uses en_US as default locale regardless of the underlying operating system but other, non Power Saver nodes display the time in the correct format. See the attached screenshot where the Power Saver nodes (orange) shows the time in 12h format while the Home Assistant nodes (blue) show the time in 24h format.

![pa](https://user-images.githubusercontent.com/16463587/213790415-fb9ccc6a-abb2-4f55-b68f-43b7fb26561b.png)

**Comment by nikee73** [comment]
Same problem here. Would be nice to have time in 24h format

**Comment by osaether** [comment]
I have looked further into this and now I believe the problem is in Home Assistant or Node Red so I am closing this issue.

**Comment by osaether** [comment]
I have looked further into this and now I am convinced that the problem is in Home Assistant or Node Red so I am closing this issue.
