### ISSUE TITLE
How to control floor heating, lower temp during night

### ISSUE THREAD

**Issue by shadowano** [ottopaulsen/node-red-contrib-power-saver#160]
Hi,

I have a bath which has floor heating, but the floor doesn't keep the heat for long. This means it heats the floor quite often. I would like to lower the temperature during night, but increase in the morning to normal temperature when price is low.

I have tested the heat capacitor nodes, but that uses as much power as it would if temp was on same temperature all the time (maybe it uses less money due to price calculation). It would maybe work better if the floor kept the temperature for a longer time.

Below is screenshot showing temperature going up and down over time.

![Screenshot_20230304_171632_Home Assistant](https://user-images.githubusercontent.com/3582807/222916885-28ccc0b4-63bf-481f-b302-64d099843f7a.jpg)

**Comment by ottopaulsen** [comment]
You could try a combination of Fixed Schedule and Lowest Price, alternatively two Lowest Price, and merge the schedule with a Schedule Merger. See doc here: https://powersaver.no/nodes/ps-strategy-fixed-schedule.html#description

**Comment by shadowano** [comment]
I ended up making it a bit different. I'm using fixed schedule to set temperature down to low temperature during night, and in the morning at 5 (where price is still low) I increase the temperature until 8 (delay trigger) where I turn the temperature a bit down again for the rest of the day. 

![image](https://user-images.githubusercontent.com/3582807/228638073-d33ebde6-e957-4b69-85de-5cb3c86f6030.png)
