### ISSUE TITLE
Problems with ps-elvia-tariff

### ISSUE THREAD

**Issue by pittbull** [ottopaulsen/node-red-contrib-power-saver#164]
Tryting to move from manually adding the tariff to using the Elvia node, but it fails with the following error:

![image](https://user-images.githubusercontent.com/1532149/228044935-7478221b-58b7-466c-afbb-d489ccbe2b76.png)

Feedback welcome.

**Comment by ottopaulsen** [comment]
Are you using the price receiver?

**Comment by pittbull** [comment]
Confirmed. Just inserted the Elvia after.

**Comment by ottopaulsen** [comment]
Can you insert a debug node before and after the Elvia node and see what goes in and out?

**Comment by pittbull** [comment]
As requested.
![image](https://user-images.githubusercontent.com/1532149/228146111-1fdee296-3c59-487f-b881-7cd699c72972.png)

**Comment by ottopaulsen** [comment]
Are you sure you are using the correct Elvia node? ps-elvia-add-tariff?
