### ISSUE TITLE
Dynamic Config parameter is not realized

### ISSUE THREAD

**Issue by jarru66** [ottopaulsen/node-red-contrib-power-saver#172]
I have defined Function node, which is getting numeric value for "hoursOn" from MQTT.
I think **dynamic config** object is correctly sent to **PS-STRATEGY-LOWEST-PRICE** -node.
It should change config dynamically, but seems that it doesn't. It's providing error/info msg: "Payload is missing priceData" and that’s true, but it should use previous price data, if I have understand correctly the docs. And at least parameter should have impact, when the price data is coming next time, but dynamic parameter is not still taking place (as seen by debug node 149).

******  Function node content ****
// The MQTT message payload is number, but this support also if the number as a string
var chargetime = parseFloat(msg.payload); // Convert the payload to a number if needed
// Create an object with the MQTT number as a parameter
var config = {
    "hoursOn": chargetime
};
// Set the output of the Function node to the object
msg.payload = config;
return msg;

***************
![image](https://github.com/ottopaulsen/node-red-contrib-power-saver/assets/120382379/b786ea0b-83e6-4786-af8b-953369d17c83)

![image](https://github.com/ottopaulsen/node-red-contrib-power-saver/assets/120382379/c5b93325-372a-4d27-84f6-b79ea463316a)

![image](https://github.com/ottopaulsen/node-red-contrib-power-saver/assets/120382379/d316a3da-fab9-47ce-b055-1d229ac44bac)

**Comment by ottopaulsen** [comment]
If you put a debug node after your function node and look at the data you are trying to send as config, you will see that it does not satisfy the spec. Te spec is [here](https://powersaver.no/nodes/dynamic-config.html). Example: 

```
"payload": {
  "name": "Lowest Price",
  "config": {
    "maxHoursToSaveInSequence": 4,
    "minSaving": 0.02
  }
}
```

The `msg.payload` object shall hold an object named `config`, but your does not. Your code `msg.payload = config` will result in a msg object similar to this:

```
"payload": {
  "hoursOn": 5
}
```

Try change that line of your code to

```
msg.payload = { config };

```

**Comment by ottopaulsen** [comment]
By the way, I am not sure it works with float. You are using parseFloat. But you can try.

**Comment by jarru66** [comment]
Excellent answer as you provided the fixing cfg part as well. I'm novise with Node-red.
I change my Function node as you guided and it works. It seems to work with parse-function too (however the currently I have input coming from MQTT as number, so parse is not needed).
Working cfg below.
****
// The MQTT message payload is number, but this support also if the number as a string
var chargetime = parseFloat(msg.payload); // Convert the payload to a number if needed

// Create an object with the MQTT number as a parameter
var config = {
    "name": "Lowest Price",
    "hoursOn": chargetime,
};

// Set the output of the Function node to the object
// msg.payload = config;  // This row was wrong
msg.payload = { config };
return msg;

![image](https://github.com/ottopaulsen/node-red-contrib-power-saver/assets/120382379/f2fc55f9-7d38-41d1-afbb-be0cec5e386d)

![image](https://github.com/ottopaulsen/node-red-contrib-power-saver/assets/120382379/8011defb-883e-4546-8081-7952377de8fb)
