### ISSUE TITLE
Feature Request: Notification by entering a geofancy zone

### ISSUE THREAD

**Issue by JanneW3** [ottopaulsen/node-red-contrib-power-saver#175]
Feature request: 

Notification function for Android Auto or Apple Car Play through Telegram, WhatsApp or Signal when entering a geofancing zone.

Optionally, values from the API interface of the car should be used such as charging status and charging goal and the possible charging speed of the wallbox.

For this it would be enough to create a data point charging schedule (type: Mixed) to keep the flow as general as possible to be able to use it in the different home automations.

**Comment by ottopaulsen** [comment]
This has nothing to do with powersaver.
