### ISSUE TITLE
error from add elvia tariff node

### ISSUE THREAD

**Issue by areeeee** [ottopaulsen/node-red-contrib-power-saver#196]
I have started to get the following error for the last few weeks:

`"Elvia tariff count mismatch. Expected 24 items, but got 0"
`

The flow has worked before and I can't remember that I have changed anything. 

I use the tibber-query node, pc-receive-price and  ps-elvia-add-tariff nodes. 
I have made a new key at Elvia and it says it's connected. I don't know where to begin troubleshooting..

**Comment by ronnyandre** [comment]
I have a similar issue where Elvia tariff node only reports `null` as price for each hour.

**Comment by le-clu** [comment]
Same here

**Comment by areeeee** [comment]
I had to change Tariff Key to "Standard". Now working again.

**Comment by magne74** [comment]
@areeeee What do you mean with "Standard"?
