### ISSUE TITLE
Power Saver don't use browser time format

### ISSUE THREAD

**Issue by Gybrsh** [ottopaulsen/node-red-contrib-power-saver#197]
Node-RED show time based on your browser locale, so for me all nodes use the **24 hour format**. 

Power Saver nodes show **AM/PM format**.

![image](https://github.com/ottopaulsen/node-red-contrib-power-saver/assets/77282014/e2cea16c-8480-4d2f-808b-174fb0de3488)

**Comment by ottopaulsen** [comment]
I am not sure why browser time format is not used, but I have changed to HH:MM format in version 4.2.0. Please try and let me know if it is ok.

**Comment by ottopaulsen** [comment]
Sorry, you need 4.2.1 for this to work.
