### ISSUE TITLE
When calculation is made and schedule spans from today to tomorrow, schedule is not correct

### ISSUE THREAD

**Issue by Swoop86** [ottopaulsen/node-red-contrib-power-saver#2]
When a schedule is made it seems it does not understand the timespan from 23:00:00 to 00:00:00/01:00:00. "min-recover" is here set to 3, so it should turn off at 02:00:00. I'm seeing the same issue when using apexcharts to import price into HA, that there is a problem at the hours 23:00 and 00:00.
![image](https://user-images.githubusercontent.com/5503114/136793674-ef2b2949-6679-47b2-beda-9a4d407597fd.png)

**Comment by ottopaulsen** [comment]
Can you please try this again, @Swoop86 ? I think it is fixed now, in version 1.0.9.

**Comment by ottopaulsen** [comment]
Great. Thanks. Closing issue.
