### ISSUE TITLE
Installing 3.0.10 returns errors

### ISSUE THREAD

**Issue by osvedman** [ottopaulsen/node-red-contrib-power-saver#21]
I'm running Node-RED 2.1.4 on a Raspberry Pi 4.

Getting these errors when installing 3.0.10:

27 Dec 19:44:38 - [info] Installing module: node-red-contrib-power-saver, version: 3.0.10
27 Dec 19:44:59 - [info] Installed module: node-red-contrib-power-saver
27 Dec 19:44:59 - [info] Added node types:
27 Dec 19:44:59 - [info]  - node-red-contrib-power-saver:power-saver : SyntaxError: Unexpected token '.' (line:62)
27 Dec 19:44:59 - [info]  - node-red-contrib-power-saver:ps-receive-price : SyntaxError: Unexpected token '.' (line:1)
27 Dec 19:44:59 - [info]  - node-red-contrib-power-saver:ps-strategy-best-save : SyntaxError: Unexpected token '.' (line:61)
27 Dec 19:44:59 - [info]  - node-red-contrib-power-saver:ps-strategy-lowest-price : SyntaxError: Unexpected token '.' (line:79)
27 Dec 19:44:59 - [info]  - node-red-contrib-power-saver:ps-elvia-config
27 Dec 19:44:59 - [info]  - node-red-contrib-power-saver:ps-elvia-tariff-types
27 Dec 19:44:59 - [info]  - node-red-contrib-power-saver:ps-elvia-tariff
27 Dec 19:44:59 - [info]  - node-red-contrib-power-saver:ps-elvia-add-tariff : SyntaxError: Unexpected token '?' (line:3)

**Comment by ottopaulsen** [comment]
What version of node do you use? (Type `node --version` to find out.)

**Comment by osvedman** [comment]
v12.22.6

**Comment by ottopaulsen** [comment]
The I suggest that you upgrade node, at least to version 14, but maybe even 16.

**Comment by osvedman** [comment]
Upgrading to Node 14 fixed this issue. Thank you.
