### ISSUE TITLE
Output 3

### ISSUE THREAD

**Issue by eirektg** [ottopaulsen/node-red-contrib-power-saver#24]
It would be practical if Output 3 could contain the current output from the Power Saver nodes.

Like this:
Object
>schedule: array[4]
>hours: array[48]
source: "Nordpool"
>config: object
**Current_output: On|Off**

**Comment by ottopaulsen** [comment]
This is done in version 3.1.2.
The property `current` is added to the output, and can have values `true` or `false`, but may also be undefined, if there is no schedule for the current time.
