### ISSUE TITLE
Website issue (guide power saver)

### ISSUE THREAD

**Issue by Mylarrito** [ottopaulsen/node-red-contrib-power-saver#27]
Something is broken in the website, and the only way to view the text in the guides is in internet explorer (:D). Tried all browsers on several computers. Just shows date of update, no text.

This element shows a 404 error:
  | https://ottopaulsen.github.io/euro.png

**Comment by ottopaulsen** [comment]
Thank you for notifying.
I think it should be ok now.

**Comment by Mylarrito** [comment]
Works in Edge and Firefox, thanks for a quick fix!
