### ISSUE TITLE
[Q] Does the "best-save" node take into account the existing schedule when prices are updated?

### ISSUE THREAD

**Issue by AlecTBM** [ottopaulsen/node-red-contrib-power-saver#28]
Thank you for the project
What I mean is when I am feeding it the prices for the next day at the evening (around 16-17), do the node take into account what the schedule have been until that point? Example, if the rule "Max per sequence" is 12 hours, and when the time is 16:00, it have been off for 10 hours, new prices for "tomorrow" is loaded, do it take it into account that the output have been of for 10 hours, and need to be turned on again in two hours? 
And does it differ if you choose "Whole data set" or "From current hour"?

**Comment by ottopaulsen** [comment]
It is supposed to take into account the schedule that has passed.
However, I am not sure this is working properly if you have selected to plan from current hour.
I will have to check that up. If you have any information that can help me, please put it in here. What I need is the prices that are sent as input to the node, as well as the complete payload on output 3, and an explanation of what is happening.

**Comment by AlecTBM** [comment]
For a test I have actually saved all the outputs from the output3 in a file for some days now (forgot to stop it). I can clean it up a bit and share it later 😊

**Comment by AlecTBM** [comment]
I have found some bugs in my handling of the prices before sending them to the best saver node, so I don't think the data I have are of any value for you. I will see if I found any problems after the fix and upload if I find something

**Comment by ottopaulsen** [comment]
In version 3.3.0, the schedule is always calculated using all data received. The schedule from current hour was removed as it was not working.

Can we close this issue?

**Comment by AlecTBM** [comment]
Yes it can be closed 😊 thank you

**Comment by AlecTBM** [comment]
I had a look now, and it seems that it do not keep the past schedule in mind.
![image](https://user-images.githubusercontent.com/1237208/154130052-1a546b03-5ee0-41e6-923b-5fe80d0a89ef.png)
This graph is the schedule in cyan (last value, old values are overwritten), and the actual state of the relay on purple.

I have all the inputs and output3 saved as json for some weeks, so I have uploaded it for february (actually the beginning of february looks quite good):
[bestsave.txt](https://github.com/ottopaulsen/node-red-contrib-power-saver/files/8073928/bestsave.txt)

**Comment by ottopaulsen** [comment]
First please verify that Node-RED actually saves data between reboots:
1. Restart Node-RED
2. Click on the node.
3. Select `Context Data` in the menu to the right.
4. Click the refresh-button in the node-section.
5. Now you should see config, lastPlan, lastPriceData as well as data for multiple dates.

Do you see those saved data?
If not, open `/config/node-red/settings.js`. It shall contain something like this:
```js
  contextStorage: {
    file: { module: "localfilesystem"},
    default: { module: "memory" }
  },
```

Please let me know what you find out.

**Comment by AlecTBM** [comment]
This is my settings:
`contextStorage: {
        default: "memoryOnly",
        memoryOnly: { module: 'memory' },
        file: { module: 'localfilesystem' }
    },`

However, this issue is not related to any restart of node red, so the saved context in memory should not been lost when the new prices are received.

**Comment by ottopaulsen** [comment]
I suggest you try the contextStorage settings I posted above.

**Comment by AlecTBM** [comment]
The schedule get saved to context, but to the default context store which is memory (same as yours settings):
![image](https://user-images.githubusercontent.com/1237208/155391413-056e92aa-1a9a-452b-bd47-ea1f0c7a4405.png)

The settings you posted should practically be the same as mine, the only difference is that I have named the default as "memoryOnly" (copy paste from the NR docs). Just to be sure I will change my settings to match yours. What are the expected result after changing the settings?

For completeness sake, here are the graph and data since the 17.2:
![image](https://user-images.githubusercontent.com/1237208/155392511-5afb5906-5d5d-424e-b55b-08da30e41ce7.png)
[bestsave.txt](https://github.com/ottopaulsen/node-red-contrib-power-saver/files/8127282/bestsave.txt)

**Comment by ottopaulsen** [comment]
I just realised that all this context is only stored in memory, so you're right. Nothing has been stored over restart. I will make a fix for this. Thanks for not giving up :-)

**Comment by AlecTBM** [comment]
No problem, and to my suprise changing the context store settings actually show a change in the graph after I did the change: 
![image](https://user-images.githubusercontent.com/1237208/155964147-79f94919-032a-4715-85a0-7aeb79bff5e6.png)
Purple is schedule and cyan is actual. 


This result is surprising for me, but there might be a bit too early to conclude. However, if this is correct, I don't think demanding a certain context store settings is the way to go 😊 ours was for all purposes identical, just that you did not name your default store, but I did.

**Comment by AlecTBM** [comment]
Apparently it was a bit too early to conclude as it again have started to not consider the past schedule.
![image](https://user-images.githubusercontent.com/1237208/156941424-8c4a1fd6-d4b9-4c05-958e-57e54e9727b8.png)
Cyan is actual, purple is schedule. Past 7 days.
Actual input and output of the node for these days.
[bestsave.txt](https://github.com/ottopaulsen/node-red-contrib-power-saver/files/8193467/bestsave.txt)
 
Note that I have not restarted or redeployed node-red in this timeframe. And my node context looks like this at the moment:
![image](https://user-images.githubusercontent.com/1237208/156941597-3aedb63d-5ee5-4780-a407-306e98fe2975.png)

Just a thought from me, I am always sending both todays and tomorrows prices. Is this correct of me? or should I only send for tomorrow since the node already know todays?

**Comment by AlecTBM** [comment]
Any ideas @ottopaulsen ?

**Comment by ottopaulsen** [comment]
Sorry, I have very little time for this at the moment.
About input prices, I always send all prices I get, that is today and tomorrow. That should not be a problem.
Are you sure you are running the latest version? I thought I had fixed so those passed days before yesterday are deleted.

**Comment by AlecTBM** [comment]
No problem, this is not a big issue 😊
I have not updated for a while to not disturb the logging and since I did not see anything in the changelog that impacted this. 
However, I am updating now.

**Comment by ottopaulsen** [comment]
As mentioned in [another issue](https://github.com/ottopaulsen/node-red-contrib-power-saver/issues/25), changes have been made to how context storage is used. Install version 3.5 to try this.

I am not sure how this relates to this issue, so please give me feedback.

Read about the changes to how context storage is used in the documentation for the [Best Save](https://powersaver.no/nodes/ps-strategy-best-save.html) and [Lowest Price](https://powersaver.no/nodes/ps-strategy-lowest-price.html) nodes. Just search for `context`.

**Comment by AlecTBM** [comment]
I have updated and will report back. Thanks

**Comment by AlecTBM** [comment]
Hello. The context store seem to work. But it still seems like it still dont take into account the existing schedule, or if it does, it is not 100% strict.

**Comment by ottopaulsen** [comment]
Guess I need to know what data you are using, what result you get and what you expect.

**Comment by ottopaulsen** [comment]
Closing due to no response
