### ISSUE TITLE
Option to resend at interval

### ISSUE THREAD

**Issue by SuperBigB** [ottopaulsen/node-red-contrib-power-saver#36]
Can we add an option to resend on/off-outputs at a set interval? For debug purposes, communications problems,  and more.

**Comment by ottopaulsen** [comment]
Now you can do this with the [sendOutput command](https://power-saver.smoky.no/nodes/ps-strategy-best-save.html#sendoutput).
Version 3.2.2.

**Comment by SuperBigB** [comment]
@ottopaulsen version 3.3.2?

**Comment by ottopaulsen** [comment]
Yes, right. Sorry. 3.3.2. 
https://www.npmjs.com/package/node-red-contrib-power-saver
