### ISSUE TITLE
[error] [api-call-service:Turn on VVB] Call-Service attempted without connection to server.

### ISSUE THREAD

**Issue by torsteinelv** [ottopaulsen/node-red-contrib-power-saver#39]
Any reason that this happens?

**Comment by ottopaulsen** [comment]
I am getting that too when I deploy flows. I think it is just Node-RED trying to call a service before the HA server is properly connected. If you can get it delayed somehow, I assume it will disappear. Would be nice if you find a solution and post it back here :-)

**Comment by torsteinelv** [comment]
Removed "Delay Connection Attempts" fixed the issue for me
