### ISSUE TITLE
[Request for new functionality] Read data directly from Nord Pool API node?

### ISSUE THREAD

**Issue by houser42** [ottopaulsen/node-red-contrib-power-saver#40]
Hello.
I am trying to use this seemingly great package just in node red with either one of the two nordpool api nodes: node-red-contrib-nordpool-api or node-red-contrib-nordpool-api-plus. Maybe I am missing something and it can already be done?

The nordpool api nodes output respectively 24 or 48 hourly pricing as an array that is very similar but not the same as the format required by this node-red-contrib-power-saver.
Example sample as starting point if you have not looked at it: 
```
object
payload: array[48]
[0 … 9]
0: object
Area: "SE3"
Timestamp: "2022-02-17 00:00"
StartTime: "2022-02-17 00:00"
EndTime: "2022-02-17 01:00"
Price: 184.82
Valuta: "SEK/MWh"
```
Or perhaps find a way to do this in a function node to convert the output from Nord Pool API to the common strategy input format.
Can you comment or suggest best practice for this please? Many thanks!

**Comment by houser42** [comment]
Thanks @ottopaulsen 

Reply much appreciated!
Any chance of a hint to get me started? A function node example somewhere?
I have searched without any success for a good starting point as I am afraid I am not 
a master of javascript. Ah well. Thanks again regardless!
Here is the complete array from the node I am using if some one has the time to take a peek, from https://github.com/Csstenersen/node-red-contrib-nordpool-api:

`{"payload":[{"Area":"SE3","Timestamp":"2022-02-18 00:00","StartTime":"2022-02-18 00:00","EndTime":"2022-02-18 01:00","Price":140.26,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 01:00","StartTime":"2022-02-18 01:00","EndTime":"2022-02-18 02:00","Price":135.49,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 02:00","StartTime":"2022-02-18 02:00","EndTime":"2022-02-18 03:00","Price":135.07,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 03:00","StartTime":"2022-02-18 03:00","EndTime":"2022-02-18 04:00","Price":135.49,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 04:00","StartTime":"2022-02-18 04:00","EndTime":"2022-02-18 05:00","Price":139.41,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 05:00","StartTime":"2022-02-18 05:00","EndTime":"2022-02-18 06:00","Price":143.12,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 06:00","StartTime":"2022-02-18 06:00","EndTime":"2022-02-18 07:00","Price":286.35,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 07:00","StartTime":"2022-02-18 07:00","EndTime":"2022-02-18 08:00","Price":1016.99,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 08:00","StartTime":"2022-02-18 08:00","EndTime":"2022-02-18 09:00","Price":1057.77,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 09:00","StartTime":"2022-02-18 09:00","EndTime":"2022-02-18 10:00","Price":1109.36,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 10:00","StartTime":"2022-02-18 10:00","EndTime":"2022-02-18 11:00","Price":1014.87,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 11:00","StartTime":"2022-02-18 11:00","EndTime":"2022-02-18 12:00","Price":954.38,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 12:00","StartTime":"2022-02-18 12:00","EndTime":"2022-02-18 13:00","Price":986.9,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 13:00","StartTime":"2022-02-18 13:00","EndTime":"2022-02-18 14:00","Price":835.94,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 14:00","StartTime":"2022-02-18 14:00","EndTime":"2022-02-18 15:00","Price":715.39,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 15:00","StartTime":"2022-02-18 15:00","EndTime":"2022-02-18 16:00","Price":794.84,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 16:00","StartTime":"2022-02-18 16:00","EndTime":"2022-02-18 17:00","Price":1007.24,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 17:00","StartTime":"2022-02-18 17:00","EndTime":"2022-02-18 18:00","Price":1205.98,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 18:00","StartTime":"2022-02-18 18:00","EndTime":"2022-02-18 19:00","Price":1250.79,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 19:00","StartTime":"2022-02-18 19:00","EndTime":"2022-02-18 20:00","Price":1231.3,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 20:00","StartTime":"2022-02-18 20:00","EndTime":"2022-02-18 21:00","Price":1164.98,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 21:00","StartTime":"2022-02-18 21:00","EndTime":"2022-02-18 22:00","Price":1134.68,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 22:00","StartTime":"2022-02-18 22:00","EndTime":"2022-02-18 23:00","Price":1052.9,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-18 23:00","StartTime":"2022-02-18 23:00","EndTime":"2022-02-19 00:00","Price":915.29,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 00:00","StartTime":"2022-02-19 00:00","EndTime":"2022-02-19 01:00","Price":265.48,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 01:00","StartTime":"2022-02-19 01:00","EndTime":"2022-02-19 02:00","Price":264.63,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 02:00","StartTime":"2022-02-19 02:00","EndTime":"2022-02-19 03:00","Price":175.96,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 03:00","StartTime":"2022-02-19 03:00","EndTime":"2022-02-19 04:00","Price":152.16,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 04:00","StartTime":"2022-02-19 04:00","EndTime":"2022-02-19 05:00","Price":136.92,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 05:00","StartTime":"2022-02-19 05:00","EndTime":"2022-02-19 06:00","Price":138.19,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 06:00","StartTime":"2022-02-19 06:00","EndTime":"2022-02-19 07:00","Price":138.82,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 07:00","StartTime":"2022-02-19 07:00","EndTime":"2022-02-19 08:00","Price":139.99,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 08:00","StartTime":"2022-02-19 08:00","EndTime":"2022-02-19 09:00","Price":145.07,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 09:00","StartTime":"2022-02-19 09:00","EndTime":"2022-02-19 10:00","Price":154.7,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 10:00","StartTime":"2022-02-19 10:00","EndTime":"2022-02-19 11:00","Price":164.22,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 11:00","StartTime":"2022-02-19 11:00","EndTime":"2022-02-19 12:00","Price":165.17,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 12:00","StartTime":"2022-02-19 12:00","EndTime":"2022-02-19 13:00","Price":168.87,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 13:00","StartTime":"2022-02-19 13:00","EndTime":"2022-02-19 14:00","Price":161.79,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 14:00","StartTime":"2022-02-19 14:00","EndTime":"2022-02-19 15:00","Price":151.2,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 15:00","StartTime":"2022-02-19 15:00","EndTime":"2022-02-19 16:00","Price":146.23,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 16:00","StartTime":"2022-02-19 16:00","EndTime":"2022-02-19 17:00","Price":166.02,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 17:00","StartTime":"2022-02-19 17:00","EndTime":"2022-02-19 18:00","Price":1057.58,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 18:00","StartTime":"2022-02-19 18:00","EndTime":"2022-02-19 19:00","Price":1213.55,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 19:00","StartTime":"2022-02-19 19:00","EndTime":"2022-02-19 20:00","Price":1159.69,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 20:00","StartTime":"2022-02-19 20:00","EndTime":"2022-02-19 21:00","Price":1005.84,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 21:00","StartTime":"2022-02-19 21:00","EndTime":"2022-02-19 22:00","Price":1013.35,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 22:00","StartTime":"2022-02-19 22:00","EndTime":"2022-02-19 23:00","Price":970.82,"Valuta":"SEK/MWh"},{"Area":"SE3","Timestamp":"2022-02-19 23:00","StartTime":"2022-02-19 23:00","EndTime":"2022-02-20 00:00","Price":712.11,"Valuta":"SEK/MWh"}],"topic":"hourly","_msgid":"9276b032c8384750"}`

**Comment by ottopaulsen** [comment]
A function node with this code would do:
```js
const priceData = msg.payload.map(h => {
    const date = h.StartTime.substring(0, 10)
    const hour = h.StartTime.substring(11, 16)
    return {
        value: h.Price / 1000.0,
        start: date + "T" + hour + ":00.000+01:00"
    }
})
return {payload: {priceData, source: "Other" }};
```

Send the prices in and send the output to the strategy node.
This will only work until DST is change from winter to rummer time. Then the `+01:00` must be changed to `+02:00`.
Of course, a date conversion that takes care of that would be better.

**Comment by houser42** [comment]
Just confirming that this works as expected. Many thanks again!
For planning purposes I would finally like to put the strategy schedule into a chart with the same timeline as the strategy price chart, so that consequences of programming becomes clear.
Could you tell me how to use a function to format the schedule object part from the strategy nodes in to a node red chart? Maybe someone has already done this?
Attached is a the chart for the price itself to make it clear. 
Many thanks for any hints or starting point flow examples
<img width="627" alt="Screenshot 2022-02-21 at 09 04 26" src="https://user-images.githubusercontent.com/15192440/154913173-6d1a980d-d5fd-4772-9b33-b2445282af06.png">
.

**Comment by ottopaulsen** [comment]
Sorry, I haven't used Node-RED charts. Looks nice.

**Comment by houser42** [comment]
Thanks for the reply @ottopaulsen regardless;)
I'll continue the experiment. Slowly but surely getting there I hope ;)

**Comment by houser42** [comment]
Hello again.
Your code has been working great since it was setuup. Very useful and many thanks again for that!

A follow up question if that is allowed?
Is there a way to request what the price is right now by using an example similar to your function example above?
I would like to Inject a timestamp and get just the price right now as a payload? Many thanks regardless!

**Comment by ottopaulsen** [comment]
These are good ideas, thanks. I will keep them in mind.

**Comment by houser42** [comment]
Many thanks for your kind reply.
Any chance you have some lines of code for a function node for now to achieve this, based on this thread's data in the first array from Feb 18? Would certainly appreciate it..

**Comment by calania** [comment]
Hello! I am also not using home assistant but want to get this node working. I tried the script @ottopaulsen made but am getting the following error in my function node

"TypeError: Cannot read properties of undefined (reading 'substring')"

Any ideas why this might be?

This was the flow I tested it with

`[
    {
        "id": "8f6ffcd899d215a7",
        "type": "nordpool-api-plus",
        "z": "a93551d4.0ad2e8",
        "name": "",
        "area": "SE4",
        "currency": "SEK",
        "action": "dayAhead",
        "x": 340,
        "y": 2280,
        "wires": [
            [
                "d9dc90b9eccf61ad"
            ]
        ]
    },
    {
        "id": "60047b6f9acd1643",
        "type": "inject",
        "z": "a93551d4.0ad2e8",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 180,
        "y": 2280,
        "wires": [
            [
                "8f6ffcd899d215a7"
            ]
        ]
    },
    {
        "id": "d9dc90b9eccf61ad",
        "type": "function",
        "z": "a93551d4.0ad2e8",
        "name": "function 1",
        "func": "const priceData = msg.payload.map(h => {\n    const date = h.StartTime.substring(0, 10)\n    const hour = h.StartTime.substring(11, 16)\n    return {\n        value: h.Price / 1000.0,\n        start: date + \"T\" + hour + \":00.000+01:00\"\n    }\n})\nreturn { payload: { priceData, source: \"Other\" } };",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 520,
        "y": 2280,
        "wires": [
            [
                "a4760ae2a0ed552e"
            ]
        ]
    },
    {
        "id": "a4760ae2a0ed552e",
        "type": "ps-receive-price",
        "z": "a93551d4.0ad2e8",
        "name": "Price Receiver",
        "x": 680,
        "y": 2280,
        "wires": [
            []
        ]
    }
]`

**Comment by ottopaulsen** [comment]
The error message you are getting means that StartTime is not found where expected, so you must check the data you send in to the node.

**Comment by calania** [comment]
Yea it seems that you are right. This is the output for me from the nordpool node

`[{"timestamp":"2023-01-28T23:00:00.000Z","price":334.98,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T00:00:00.000Z","price":330.03,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T01:00:00.000Z","price":319.34,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T02:00:00.000Z","price":317.76,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T03:00:00.000Z","price":322.15,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T04:00:00.000Z","price":303.8,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T05:00:00.000Z","price":306.84,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T06:00:00.000Z","price":328.46,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T07:00:00.000Z","price":347.82,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T08:00:00.000Z","price":352.43,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T09:00:00.000Z","price":386.76,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T10:00:00.000Z","price":382.71,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T11:00:00.000Z","price":381.47,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T12:00:00.000Z","price":393.4,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T13:00:00.000Z","price":386.99,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T14:00:00.000Z","price":366.28,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T15:00:00.000Z","price":390.48,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T16:00:00.000Z","price":412.54,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T17:00:00.000Z","price":392.28,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T18:00:00.000Z","price":350.86,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T19:00:00.000Z","price":321.14,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T20:00:00.000Z","price":292.44,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T21:00:00.000Z","price":282.31,"currency":"SEK","area":"SE4"},{"timestamp":"2023-01-29T22:00:00.000Z","price":206.44,"currency":"SEK","area":"SE4"}]`

Will have to see if I can modify your script to make it work

**Comment by calania** [comment]
I have modified the function node and am now getting the following output from the function node

`{"priceData":[{"value":0.33498,"start":"2023-01-28T23:00:00.000+01:00"},{"value":0.33003,"start":"2023-01-29T00:00:00.000+01:00"},{"value":0.31933999999999996,"start":"2023-01-29T01:00:00.000+01:00"},{"value":0.31776,"start":"2023-01-29T02:00:00.000+01:00"},{"value":0.32215,"start":"2023-01-29T03:00:00.000+01:00"},{"value":0.3038,"start":"2023-01-29T04:00:00.000+01:00"},{"value":0.30684,"start":"2023-01-29T05:00:00.000+01:00"},{"value":0.32846,"start":"2023-01-29T06:00:00.000+01:00"},{"value":0.34782,"start":"2023-01-29T07:00:00.000+01:00"},{"value":0.35243,"start":"2023-01-29T08:00:00.000+01:00"},{"value":0.38676,"start":"2023-01-29T09:00:00.000+01:00"},{"value":0.38271,"start":"2023-01-29T10:00:00.000+01:00"},{"value":0.38147000000000003,"start":"2023-01-29T11:00:00.000+01:00"},{"value":0.39339999999999997,"start":"2023-01-29T12:00:00.000+01:00"},{"value":0.38699,"start":"2023-01-29T13:00:00.000+01:00"},{"value":0.36628,"start":"2023-01-29T14:00:00.000+01:00"},{"value":0.39048,"start":"2023-01-29T15:00:00.000+01:00"},{"value":0.41254,"start":"2023-01-29T16:00:00.000+01:00"},{"value":0.39227999999999996,"start":"2023-01-29T17:00:00.000+01:00"},{"value":0.35086,"start":"2023-01-29T18:00:00.000+01:00"},{"value":0.32114,"start":"2023-01-29T19:00:00.000+01:00"},{"value":0.29244,"start":"2023-01-29T20:00:00.000+01:00"},{"value":0.28231,"start":"2023-01-29T21:00:00.000+01:00"},{"value":0.20643999999999998,"start":"2023-01-29T22:00:00.000+01:00"}],"source":"Other"}`

But when I send that data into the price receiver node I get the following error

TypeError: Cannot destructure property 'priceData' of 'getPriceData(...)' as it is null.

Any idea what might be wrong with the payload?

**Comment by ottopaulsen** [comment]
Yes, now you already have the [format](https://powersaver.no/nodes/strategy-input.html) that the strategy nodes need, so you can skip the price receiver node.

**Comment by houser42** [comment]
I hope it is appropriate to add this to the old issue.
Basically  as we know that the Node Red Dashboard V1.0  is no longer developed and we all need to migrate to version 2 of that package:
https://dashboard.flowfuse.com/getting-started.html
My question is if the code you gave a year ago can be updated to work with the new 2.0ui-chart  version? I hav tried to make it work but can not get past it as yet.

I would certainly appreciate if you can have a look when you have time?
Many thanks. 

This is the flow that works with V1 
also the new V2 ui-chart is attached
```
[
    {
        "id": "6e3a9d60498cf985",
        "type": "function",
        "z": "df632f65fb380b66",
        "name": "",
        "func": "var msg1 = {}\nfor (var i = 0; i<msg.payload.length;i++){\n    msg1 = {\n        topic:msg.payload[i].Area + \" \" + msg.payload[i].Valuta, \n        payload:msg.payload[i].Price, \n        timestamp:msg.payload[i].Timestamp,\n        }\n    node.send(msg1)\n    }\nreturn;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 240,
        "y": 260,
        "wires": [
            [
                "5d41fcb90b8f17e6"
            ]
        ]
    },
    {
        "id": "5d41fcb90b8f17e6",
        "type": "function",
        "z": "df632f65fb380b66",
        "name": "price",
        "func": "msg.payload = msg.payload / 1000 * 1.01 * 1.25 + 0.9356;\nreturn msg;",
        "outputs": 1,
        "timeout": "",
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 410,
        "y": 260,
        "wires": [
            [
                "596b48101363863d",
                "4e6dcf57141122aa",
                "aede765b1ce8ba93"
            ]
        ]
    },
    {
        "id": "2b9dd5e5702ac6be",
        "type": "nordpool-api",
        "z": "df632f65fb380b66",
        "area": "SE3",
        "currency": "SEK",
        "timeSpan": "hourly",
        "x": 240,
        "y": 220,
        "wires": [
            [
                "6e3a9d60498cf985"
            ]
        ]
    },
    {
        "id": "596b48101363863d",
        "type": "ui_chart",
        "z": "df632f65fb380b66",
        "name": "price V 1.0",
        "group": "",
        "order": 15,
        "width": 13,
        "height": 5,
        "label": "",
        "chartType": "line",
        "legend": "false",
        "xformat": "dd HH:mm",
        "interpolate": "linear",
        "nodata": "",
        "dot": true,
        "ymin": "0",
        "ymax": "5",
        "removeOlder": "48",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "useUTC": false,
        "colors": [
            "#ff9300",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "outputs": 1,
        "useDifferentColor": false,
        "className": "",
        "x": 670,
        "y": 240,
        "wires": [
            []
        ]
    },
    {
        "id": "aede765b1ce8ba93",
        "type": "ui-chart",
        "z": "df632f65fb380b66",
        "group": "",
        "name": "price V 2.0",
        "label": "",
        "order": 2,
        "chartType": "line",
        "category": "topic",
        "categoryType": "msg",
        "xAxisLabel": "kl",
        "xAxisProperty": "",
        "xAxisPropertyType": "property",
        "xAxisType": "time",
        "xAxisFormat": "",
        "xAxisFormatType": "HH:mm",
        "yAxisLabel": "kr",
        "yAxisProperty": "",
        "ymin": "0",
        "ymax": "5",
        "action": "append",
        "stackSeries": false,
        "pointShape": "false",
        "pointRadius": "3",
        "showLegend": false,
        "removeOlder": "48",
        "removeOlderUnit": "3600",
        "removeOlderPoints": "",
        "colors": [
            "#0095ff",
            "#ff0000",
            "#ff7f0e",
            "#2ca02c",
            "#a347e1",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "textColor": [
            "#ffffff"
        ],
        "textColorDefault": false,
        "gridColor": [
            "#7a7a7a"
        ],
        "gridColorDefault": false,
        "width": "20",
        "height": "4",
        "className": "",
        "x": 670,
        "y": 300,
        "wires": [
            []
        ]
    },
    {
        "id": "4e6dcf57141122aa",
        "type": "debug",
        "z": "df632f65fb380b66",
        "name": "price V2",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": true,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "payload",
        "statusType": "auto",
        "x": 660,
        "y": 180,
        "wires": []
    }
]
```
