### ISSUE TITLE
Issue with Power saver/elvia tariff and/or Node Red

### ISSUE THREAD

**Issue by Mylarrito** [ottopaulsen/node-red-contrib-power-saver#49]
Not getting any "signal" through the flow this morning (after updating HA-core to latest version). Also getting quite a few 502 gateway errors in Node Red in general.

Log snip:
31 Mar 08:35:49 - [info] [ps-strategy-best-save:Best Save] Switching on in 8650360 milliseconds
31 Mar 08:35:50 - [red] Uncaught Exception:
31 Mar 08:35:50 - [error] FetchError: invalid json response body at https://elvia.azure-api.net/grid-tariff/api/1/tariffquery?TariffKey=private_tou_daynight1&StartTime=2022-03-31T00:00:00&EndTime=2022-04-01T00:00:00 reason: Unexpected token S in JSON at position 0
    at /config/node-red/node_modules/node-fetch/lib/index.js:273:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022/03/31 08:35:51 [error] 619#619: *971 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "homeassistant.local:8123"

31 Mar 08:28:41 - [red] Uncaught Exception:
31 Mar 08:28:41 - [error] FetchError: invalid json response body at https://elvia.azure-api.net/grid-tariff/api/1/tariffquery?TariffKey=private_tou_daynight1&StartTime=2022-03-31T00:00:00&EndTime=2022-04-01T00:00:00 reason: Unexpected token S in JSON at position 0
    at /config/node-red/node_modules/node-fetch/lib/index.js:273:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022/03/31 08:28:42 [error] 619#619: *620 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "homeassistant.local:8123"
[08:28:43] INFO: Starting Node-RED...
2022/03/31 08:28:44 [error] 619#619: *620 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "homeassistant.local:8123"
2022/03/31 08:28:45 [error] 619#619: *620 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "homeassistant.local:8123"
2022/03/31 08:28:46 [error] 619#619: *620 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "homeassistant.local:8123"

**Comment by ottopaulsen** [comment]
Is this still a problem? My Elvia nodes are working fine today.

**Comment by Mylarrito** [comment]
It's fixed, something was broken for a handful of hours but was fixed by someone :)
