### ISSUE TITLE
Multiple homes Tibber

### ISSUE THREAD

**Issue by thomasja27** [ottopaulsen/node-red-contrib-power-saver#5]
Hi,
Thank you for creating this project, exactly what I'm looking for. But I have encountered a problem. I have 2 houses with tibber but only one of them has an active subscription. So the first house does not come up with any prices when I send a request with the tibber-query node.
When I query with your tibber sample code:
`{
  viewer {
    homes {
      currentSubscription{
        priceInfo{
          today {
            total
            startsAt
          }
          tomorrow {
            total
            startsAt
          }
        }
      }
    }
  }
}`

I get the following response:

`{
  "data": {
    "viewer": {
      "homes": [
        {
          "currentSubscription": {
            "priceInfo": {
              "today": [],
              "tomorrow": []
            }
          }
        },
        {
          "currentSubscription": {
            "priceInfo": {
              "today": [
                {
                  "total": 1.3172,
                  "startsAt": "2021-12-01T00:00:00.000+01:00"
                },
                {
                  "total": 1.1089,
                  "startsAt": "2021-12-01T01:00:00.000+01:00"
                },
                {
                  "total": 1.01,
                  "startsAt": "2021-12-01T02:00:00.000+01:00"
                },
                {
                  "total": 0.9748,
                  "startsAt": "2021-12-01T03:00:00.000+01:00"
                },
                {
                  "total": 1.0054,
                  "startsAt": "2021-12-01T04:00:00.000+01:00"
                },
                {
                  "total": 1.1512,
                  "startsAt": "2021-12-01T05:00:00.000+01:00"
                },
                {
                  "total": 1.1923,
                  "startsAt": "2021-12-01T06:00:00.000+01:00"
                },
                {
                  "total": 1.2452,
                  "startsAt": "2021-12-01T07:00:00.000+01:00"
                },
                {
                  "total": 1.2453,
                  "startsAt": "2021-12-01T08:00:00.000+01:00"
                },
                {
                  "total": 1.2477,
                  "startsAt": "2021-12-01T09:00:00.000+01:00"
                },
                {
                  "total": 1.2474,
                  "startsAt": "2021-12-01T10:00:00.000+01:00"
                },
                {
                  "total": 1.2392,
                  "startsAt": "2021-12-01T11:00:00.000+01:00"
                },
                {
                  "total": 1.2359,
                  "startsAt": "2021-12-01T12:00:00.000+01:00"
                },
                {
                  "total": 1.2372,
                  "startsAt": "2021-12-01T13:00:00.000+01:00"
                },
                {
                  "total": 1.2408,
                  "startsAt": "2021-12-01T14:00:00.000+01:00"
                },
                {
                  "total": 1.2422,
                  "startsAt": "2021-12-01T15:00:00.000+01:00"
                },
                {
                  "total": 1.262,
                  "startsAt": "2021-12-01T16:00:00.000+01:00"
                },
                {
                  "total": 1.2604,
                  "startsAt": "2021-12-01T17:00:00.000+01:00"
                },
                {
                  "total": 1.251,
                  "startsAt": "2021-12-01T18:00:00.000+01:00"
                },
                {
                  "total": 1.2267,
                  "startsAt": "2021-12-01T19:00:00.000+01:00"
                },
                {
                  "total": 1.2522,
                  "startsAt": "2021-12-01T20:00:00.000+01:00"
                },
                {
                  "total": 1.1716,
                  "startsAt": "2021-12-01T21:00:00.000+01:00"
                },
                {
                  "total": 0.8986,
                  "startsAt": "2021-12-01T22:00:00.000+01:00"
                },
                {
                  "total": 0.7402,
                  "startsAt": "2021-12-01T23:00:00.000+01:00"
                }
              ],
              "tomorrow": []
            }
          }
        }
      ]
    }
  }
}`

As you can see, the first house comes up without any data, then the second comes afterwards with prices.
In node red i get following debug message from the Power Saver node: "Payload has no data"

I have also tried to query data on the specific house I want the prices from:
`{
  viewer {
    home(id:"5e61352f-f911-4cc2-addd-e81ce34e5547"){
      currentSubscription{
        priceInfo{
          today {
            total
            startsAt
          }
          tomorrow {
            total
            startsAt
          }
        }
      }
    }
  }
}
`
Then I get the following response:¨

`{
  "data": {
    "viewer": {
      "home": {
        "currentSubscription": {
          "priceInfo": {
            "today": [
              {
                "total": 1.3172,
                "startsAt": "2021-12-01T00:00:00.000+01:00"
              },
              {
                "total": 1.1089,
                "startsAt": "2021-12-01T01:00:00.000+01:00"
              },
              {
                "total": 1.01,
                "startsAt": "2021-12-01T02:00:00.000+01:00"
              },
              {
                "total": 0.9748,
                "startsAt": "2021-12-01T03:00:00.000+01:00"
              },
              {
                "total": 1.0054,
                "startsAt": "2021-12-01T04:00:00.000+01:00"
              },
              {
                "total": 1.1512,
                "startsAt": "2021-12-01T05:00:00.000+01:00"
              },
              {
                "total": 1.1923,
                "startsAt": "2021-12-01T06:00:00.000+01:00"
              },
              {
                "total": 1.2452,
                "startsAt": "2021-12-01T07:00:00.000+01:00"
              },
              {
                "total": 1.2453,
                "startsAt": "2021-12-01T08:00:00.000+01:00"
              },
              {
                "total": 1.2477,
                "startsAt": "2021-12-01T09:00:00.000+01:00"
              },
              {
                "total": 1.2474,
                "startsAt": "2021-12-01T10:00:00.000+01:00"
              },
              {
                "total": 1.2392,
                "startsAt": "2021-12-01T11:00:00.000+01:00"
              },
              {
                "total": 1.2359,
                "startsAt": "2021-12-01T12:00:00.000+01:00"
              },
              {
                "total": 1.2372,
                "startsAt": "2021-12-01T13:00:00.000+01:00"
              },
              {
                "total": 1.2408,
                "startsAt": "2021-12-01T14:00:00.000+01:00"
              },
              {
                "total": 1.2422,
                "startsAt": "2021-12-01T15:00:00.000+01:00"
              },
              {
                "total": 1.262,
                "startsAt": "2021-12-01T16:00:00.000+01:00"
              },
              {
                "total": 1.2604,
                "startsAt": "2021-12-01T17:00:00.000+01:00"
              },
              {
                "total": 1.251,
                "startsAt": "2021-12-01T18:00:00.000+01:00"
              },
              {
                "total": 1.2267,
                "startsAt": "2021-12-01T19:00:00.000+01:00"
              },
              {
                "total": 1.2522,
                "startsAt": "2021-12-01T20:00:00.000+01:00"
              },
              {
                "total": 1.1716,
                "startsAt": "2021-12-01T21:00:00.000+01:00"
              },
              {
                "total": 0.8986,
                "startsAt": "2021-12-01T22:00:00.000+01:00"
              },
              {
                "total": 0.7402,
                "startsAt": "2021-12-01T23:00:00.000+01:00"
              }
            ],
            "tomorrow": []
          }
        }
      }
    }
  }
}`

In node red i get following debug message from the Power Saver node: "TypeError: Cannot read property '0' of undefined"

Looks like Power Saver someone does not understand the data coming since it is now called home and not homes? My code skills are not good, so I'm not getting anywhere with this.

**Comment by ottopaulsen** [comment]
Hi, and thanks for reporting this issue. You are right, the node is currently hard-coded to using home number 0. I can see now that I should have used a slightly different query to get prices for one specific home, but the response would be different, so it is not just to change the query. I will take a look at this in the future, but it will take a few weeks, as I am working on another big change right now.

As a workaround I suggest that you insert a node between the Tibber query and the Power Saver node, that removes the first home from the tibber data. You can do this with a function-node, if you can code Javascript, or maybe easier with a change node. I haven't tried, and have no time just now, but let me know if you need help.

Otto

**Comment by ottopaulsen** [comment]
This is now resolved in version 3. Please take a look in the [documentation](https://ottopaulsen.github.io/node-red-contrib-power-saver/guide/#get-price-data).
