### ISSUE TITLE
Stopped working 5 april 2022

### ISSUE THREAD

**Issue by torsteinelv** [ottopaulsen/node-red-contrib-power-saver#53]
On the price receaver i payload has no data and on best save i get no scedule. This happend without changing anyting.

**Comment by torsteinelv** [comment]
Where can i find this?

**Comment by ottopaulsen** [comment]
Sorry for the delay, I have been away for some time. 
You attach a debug node next to the price receiver node, and send it the same input as the price receiver node is getting.
Then, when data is received, the debug node will print it to the debug window, where you can copy it and paste it here.
You can read about this in the [Node-RED docs](https://nodered.org/docs/user-guide/editor/sidebar/debug).

**Comment by ottopaulsen** [comment]
Is this still a problem, or can we close this issue?

**Comment by ottopaulsen** [comment]
Closing due to no response.
