### ISSUE TITLE
Support for the new capacity part of the grid tariff

### ISSUE THREAD

**Issue by ottopaulsen** [ottopaulsen/node-red-contrib-power-saver#58]
I am writing this in Norwegian, since the issue currently is relevant in Norway.

Jeg ønsker å lage støtte for det nye kapasitetsleddet i PowerSaver. Målet er å hjelpe til med å holde seg under grensen for neste trinn (eller et ønsket trinn).

Reglene for kapasitetsleddet begynner å bli definert nå, og så vidt jeg kan se er de som følger:

_Man finner høyeste timesforbruk for hver dag i måneden, plukker ut de tre høyeste av disse, og beregner gjennomsnittet av dem. Tallet man får bestemmer hvilket trinn man havner på._

### Funksjonalitet

Funksjon nummer en vil være å beregne hvilket trinn man er på ut fra forbruk for alle avsluttede time i måneden. Dette er forholdsvis enkelt, og gir ingen utfordring.

Funksjon nummer to vil være å varsle eller ta aksjon dersom forbruk for inneværende time står i fare for å bli for høyt. Så vidt jeg kan se er inneværende time det eneste man kan gjøre noe med. Men hva skal man gjøre? Dette er det ikke noe enkelt fasitsvar på. Se vurderinger nedenfor.

### Hvordan estimere totalforbruk for inneværende time?

Jeg tenker at man kan se på forbruket hittil i inneværende time, og estimere totalt forbruk for hele timen. Det tallet kan være grunnlag for reaksjon. Men hvordan estimere totalforbruk for hele timen? Skal man bruke gjennomsnitt hittil i timen? (Det blir ikke så interessant i starten av timen.) Eller skal man anta at man bruker like mye resten av timen som man gjør akkurat nå? Eller at snittet for resten av timen blir som snittet de siste x sekundene/minuttene?

Hva er beste måten å vurdere dette på?

### Hvor stor forbruk er ille?

Hvor stort skal estimert forbruk for inneværende time være før det er grunnlag for reaksjon? Dette er kanskje litt lettere å svare på. Så lenge estimatet ligger under verste time hittil i dag, er det ingen grunn til reaksjon. Hvis det ligger an til å bli dagens verste time, men under 3. verste timen hittil å måneden, er det heller ingen grunn til reaksjon. Hvis den ligger mellom 2. og 3. verste time hittil i måneden, men snittet av denne og de to verste er under neste trinn (evt. med et lite buffer), er det heller ingen grunn til reaksjon. 

Men hvis timen er verst i dag, og verre enn 2. verste timen hittil i måneden, da er det grunn til å begynne å være forsiktig, selv om snittet av denne og de to andre verste ikke er over neste trinn, siden denne timen kan bidra til økt snitt sammen med en verre time som kommer senere i måneden. Og er den verre enn verste time hittil i måneden er det enda litt større grunn til å være obs, selv om snittet fortsatt ikke er over neste trinn.

Når inneværende time er blant de tre verste hittil i måneden, og snittet av de tre timene er over neste trinn, da er det virkelig grunn til å ta aksjon. Da står man i betydelig fare for å få en høyere strømregning.

Man får altså minst to grenseverdier her. En som øker sjansen for å gå over i neste trinn, og en der man sikkert går over i neste trinn, om man ikke tar affære. `Warning` og `Alarm`, kanskje?

### Reaksjoner

Hvordan skal man så reagere? Her kan man tenke seg mange muligheter.

* Man kan sende ut et tall i kW som er det man må spare resten av timen for å komme under grensen igjen. Kan evt. være ett tall for warning og ett for alarm.
* Man kan sette opp en liste med enheter man skal slå av i prioritert rekkefølge, og slå dem av en etter en inntil man sparer nok. Om situasjonen bedrer seg i løpet av timen kan man evt. vurdere å slå på igjen, i motsatt rekkefølge. En slik liste bør kanskje inneholde informasjon om antatt effekt som spares.
* Man kan sende notifikasjoner når warning eller alarm oppstår.
* Hva mer?

### Tilbakemeldinger ønskes

Jeg ønsker tilbakemelding på det som er skrevet ovenfor, og eventuelt forslag til flere måter å vurdere dette på.

**Comment by jkaberg** [comment]
Hei @ottopaulsen, dette er intressant. Parallelt til Power Saver som jeg nå prøver ut kjører jeg allerede en veldig enkel versjon med styring utefra akkumelert forbruk for inneværende time med terskelverdier som styrer hvilke enheter som skal skrues av, og nullstilles etter hel time. Nok så enkel, og gjør jobben greit nok.

Utfordringen med min tilnærming er at jeg i kombinasjon med power saver overstyrer power saver, og med noen enkle grep kan jeg jobbe meg rundt dette - men jeg tenkte legge frem min innfallsvinkel/tilnærming som du eventuelt kan ta med i vurderingen din😄

**Comment by ottopaulsen** [comment]
Løsning implementert i dette eksempelet: https://powersaver.no/examples/example-grid-tariff-capacity-part.html#introduction
