### ISSUE TITLE
Problemer med regulering

### ISSUE THREAD

**Issue by alillebakk** [ottopaulsen/node-red-contrib-power-saver#6]
Hei.
Opplever av og til noe rar regulering. Eksempelvis idag hvor prisen doblet seg fra ca kl 07, men power-saver skrudde ikke av før litt over kl 10.

Har du noe tips til hva som kan være feil her ? Se bilder under

![image](https://user-images.githubusercontent.com/2675444/144826563-ad802399-085e-4998-9764-8df48975b92b.png)

![image](https://user-images.githubusercontent.com/2675444/144826628-04d38778-9a58-4a7a-8e58-81bde3f2dc6a.png)

**Comment by alillebakk** [comment]
Her visualisert i samme graf så det er lettere å se, lilla linje = 3 er når bereder er skrudd på fra Power-Saver
![image](https://user-images.githubusercontent.com/2675444/144830621-8f1bacfc-65aa-430d-b2dc-ef272fb02010.png)

**Comment by alillebakk** [comment]
Output nå idag fra power-saver :

{"schedule":[
{"time":"2021-12-06T00:00:00+01:00","value":false},
{"time":"2021-12-06T05:00:00+01:00","value":true},
{"time":"2021-12-06T10:00:00+01:00","value":false},
{"time":"2021-12-06T22:00:00+01:00","value":true}],

"hours":[
{"price":1.137,
"onOff":false,
"start":"2021-12-06T00:00:00+01:00",
"saving":0.183},

{"price":1,
"onOff":false,
"start":"2021-12-06T01:00:00+01:00",
"saving":0.046},

{"price":0.963,
"onOff":false,
"start":"2021-12-06T02:00:00+01:00",
"saving":0.009},

{"price":0.963,
"onOff":false,
"start":"2021-12-06T03:00:00+01:00",
"saving":0.009},

{"price":0.988,
"onOff":false,
"start":"2021-12-06T04:00:00+01:00",
"saving":0.034},

{"price":0.954,
"onOff":true,
"start":"2021-12-06T05:00:00+01:00",
"saving":null},

{"price":1.118,
"onOff":true,
"start":"2021-12-06T06:00:00+01:00",
"saving":null},

{"price":1.837,
"onOff":true,
"start":"2021-12-06T07:00:00+01:00",
"saving":null},

{"price":2.494,
"onOff":true,
"start":"2021-12-06T08:00:00+01:00",
"saving":null},

{"price":2.494,
"onOff":true,
"start":"2021-12-06T09:00:00+01:00",
"saving":null},

{"price":2.494,
"onOff":false,
"start":"2021-12-06T10:00:00+01:00",
"saving":1.518},

{"price":1.899,
"onOff":false,
"start":"2021-12-06T11:00:00+01:00",
"saving":0.923},

{"price":1.55,
"onOff":false,
"start":"2021-12-06T12:00:00+01:00",
"saving":0.574},

{"price":1.922,
"onOff":false,
"start":"2021-12-06T13:00:00+01:00",
"saving":0.946},

{"price":1.98,
"onOff":false,
"start":"2021-12-06T14:00:00+01:00",
"saving":1.004},

{"price":2.012,
"onOff":false,
"start":"2021-12-06T15:00:00+01:00",
"saving":1.036},

{"price":1.975,
"onOff":false,
"start":"2021-12-06T16:00:00+01:00",
"saving":0.999},

{"price":1.975,
"onOff":false,
"start":"2021-12-06T17:00:00+01:00",
"saving":0.999},

{"price":1.974,
"onOff":false,
"start":"2021-12-06T18:00:00+01:00",
"saving":0.998},

{"price":1.418,
"onOff":false,
"start":"2021-12-06T19:00:00+01:00",
"saving":0.442},

{"price":1.346,
"onOff":false,
"start":"2021-12-06T20:00:00+01:00",
"saving":0.37},

{"price":1.128,
"onOff":false,
"start":"2021-12-06T21:00:00+01:00",
"saving":0.152},

{"price":0.976,
"onOff":true,
"start":"2021-12-06T22:00:00+01:00",
"saving":null},

{"price":1.06,
"onOff":true,
"start":"2021-12-06T23:00:00+01:00",
"saving":null}],

"source":"Nordpool",
"config":
{"maxHoursToSaveInSequence":"12",
"minHoursOnAfterMaxSequenceSaved":"1",
"minSaving":0.02,
"sendCurrentValueWhenRescheduling":true,
"outputIfNoSchedule":true,
"scheduleOnlyFromCurrentTime":false}}

**Comment by ottopaulsen** [comment]
Hei

Ja, jeg ser hva som skjer her.
Du har satt en begrensning på 12 timer.
Systemet antar at den strømmen du sparer når det er av forbrukes den første timen etter at det skrus på.
Den beregner forskjellen mellom hver enkelt av-time mot første på-time, og så summeres disse forskjellene.

Hvis systemet skulle skrudd av en time tidligere, ville den også skrudd på en time tidligere, pga. 12-timersbegrensningen.
Da ville besparelsen på alle timene blitt lavere, og i sum ville du spart mindre på dette enn på den valgte løsningen.

Håper dette var forståelig :-)

Otto

**Comment by alillebakk** [comment]
Takker for svar. Og forresten flott arbeid med å lage denne, interessen rundt dette vil nok bare øke fremover :)

Jeg trodde at den 12 timer begrensningen jeg satt var bare en begrensning på hvor lenge jeg ville tillate at utgangen var AV sammenhengende. Så jeg tenkte der her er en fordel med høyt tall for å unngå at den skrudde på menst prisen fortsatt var høy på grunn av makstid av.

Men da tolker jeg deg sånn at jeg bør sette denne lavere ?
Hvordan ville du satt innstillingene om du ønsket å oppnå det jeg har tegnet på under ? 
Rød strek er AV og blå strek er PÅ

![image](https://user-images.githubusercontent.com/2675444/144851914-39e4fd20-6dd1-4615-b728-42272f805e22.png)

**Comment by ottopaulsen** [comment]
Du trodde riktig om 12-timersbegrensningen. Den timen innimellom der er jo fortsatt mye høyere enn den som kommer etterpå, så derfor tas den med.

Du kan jo prøve med 6 eller 8 timer, men om du kan ha den av i 12 timer, så sparer du sikkert mest på det.

**Comment by ottopaulsen** [comment]
Closing this issue, as it seems to be resolved.
