### ISSUE TITLE
Request for more data in the schedule array output

### ISSUE THREAD

**Issue by eirektg** [ottopaulsen/node-red-contrib-power-saver#60]
Would it be possible to put in these values in the schedule array?
![image](https://user-images.githubusercontent.com/48910831/173539436-beaa6289-7839-46b1-9421-a97338de4613.png)

In some cases i would like to override the output based on the lenght of the "on" period.

**Comment by eirektg** [comment]
Thank you. I agree about the name

**Comment by ottopaulsen** [comment]
New feature implemented in version 3.6.0.
Please try it out and report back here how it goes.

**Comment by eirektg** [comment]
> New feature implemented in version 3.6.0. Please try it out and report back here how it goes.

Installed and tested on both Best Save and Lowest Price nodes, and it works like a charm :-)
