### ISSUE TITLE
question price below

### ISSUE THREAD

**Issue by kuradi** [ottopaulsen/node-red-contrib-power-saver#61]
i wondering how is possible if i want only grab hours when price is below certain number, i mean for example 5 best hours below 0.15?

**Comment by kuradi** [comment]
> What if there is no prive below that level?

then anser will be false ofcourse :)

> Anyway, this can probably be doe by combining with other standard nodes.

you mean switch or smthg?

**Comment by ottopaulsen** [comment]
Or maybe filter or at least the function node can fix it.
I am on vacation now, so I cannot give an example.
Please remind me in 2-3 weeks if you haven’t solved it by then. Then I can give an example.

**Comment by kuradi** [comment]
> Or maybe filter or at least the function node can fix it. I am on vacation now, so I cannot give an example. Please remind me in 2-3 weeks if you haven’t solved it by then. Then I can give an example.

reminder :)

**Comment by ottopaulsen** [comment]
Thanks for the reminder. When thinking about this, this is not so easy. I should make it a feature on the node.

**Comment by ottopaulsen** [comment]
New feature implemented in version 3.6.0.
Se [doc for Lowest Price node](https://powersaver.no/nodes/ps-strategy-lowest-price.html#configuration).
Please try it out and report back here how it works.

**Comment by kuradi** [comment]
yes sir, this is perfect! thank you!
now... i try to get those hours to show in ha.... ive been checking https://powersaver.no/examples/example-visualize-on-off/example-visualize-on-off.html#introductionithout no luck... i just want to show for example: 12.00, 13.00, 14,00 without bells and whistles which apex card is offering. help?

**Comment by ottopaulsen** [comment]
I am not an expert on that. Yo should ask in the Home Assistant Norge FB-group.

**Comment by ottopaulsen** [comment]
Closing this as he feature is done
