### ISSUE TITLE
Not working after changes in the Elvia API

### ISSUE THREAD

**Issue by osvedman** [ottopaulsen/node-red-contrib-power-saver#62]
Hello, your nodes now return a 404 for me.

Perhaps related to recent changes in the API? See "[Old pilot function calls have been removed from the API](https://elvia.portal.azure-api.net/issues/62bf4be39f718c06882d2e2a)"

**Comment by ottopaulsen** [comment]
I assume you are using one of the Elvia nodes?
Yes, I think they are failing now.
Will look into it at some time soon.

**Comment by osvedman** [comment]
Yes, Elvia. Thank you!

**Comment by ottopaulsen** [comment]
Jeg har nettopp lagt ut ny versjon som jeg tror skal ha fikset problemet med Elvia-noden. Usikker på om jeg fortsatt plukker ut riktig tall for nettleie. Fint om du sjekker om den virker og gir tilbakemelding.

**Comment by osvedman** [comment]
Jeg skal oppdatere så snart Node-RED finner den nye versjonen.

Jeg var i kontakt med Elvia tidligere denne uka, og da fikk jeg vite at riktig tall for nettleie skal ligge under tariffnøkkel "standard".

**Comment by osvedman** [comment]
Har fått oppdatert nå og skjønner nå hva du mente med å hente ut riktige priser.
Det ser ut som du henter riktige elementer fra responsen!
