### ISSUE TITLE
When schedule is to start at 00:00:00 it does not execute

### ISSUE THREAD

**Issue by Swoop86** [ottopaulsen/node-red-contrib-power-saver#7]
Not sure if this is a reoccurring issue or a one-time bug, but the schedule did not send an on command (been working pretty much flawlessly the last few weeks) to turn on. Cannot see that the turn on command is executed in the logbook and the switch was left in the off state.
![image](https://user-images.githubusercontent.com/5503114/145653570-79fb8dd5-1f20-4c6f-83cd-b2fb44bf1321.png)

**Comment by ottopaulsen** [comment]
Hi, and thanks for reporting.

I need some more information to figure this out. I guess it is a little late, but I need the full output from output 3 on the node to be able to investigate.

**Comment by Swoop86** [comment]
False alarm, did some updating that caused the "call service node" not to send the trigger to HA without specifying something in the "data" field.
