### ISSUE TITLE
If ps-elvia-add-tariff fails to authenticate, Node Red will crash and refuse to start.

### ISSUE THREAD

**Issue by phellarv** [ottopaulsen/node-red-contrib-power-saver#75]
How to replicate:
1) Add ps-elvia-add-tariff.
2) Use bogus (or not active) API key from Elvia.
3) Deploy.
It then fails to get Tariff.
If you then remove ps-elvia-add-tariff, and then try to deploy, you get an "502 Bad Gateway" error, and Node Red crashes.
It will not start again.

**Comment by ottopaulsen** [comment]
Got love tonight :-)
Fix is done in version 3.6.2. Should be published before midnight if everything goes well.
Please try it out and report back here.

**Comment by Wiigian** [comment]
I've updated and tested this, and I can confirm that it is now working for me! 
The API key I used has not been changed, it was correct also when node-red crashed earlier.

**Comment by phellarv** [comment]
It is not crashing now, but I still get Unauthorized when using the api-key from Elvia.

**Comment by Wiigian** [comment]
> It is not crashing now, but I still get Unauthorized when using the api-key from Elvia.

Are you using the API key from "Min Side" at Elvia, or the Elvia developer portal?

**Comment by phellarv** [comment]
Min Side. Should I be using the developer one?

**Comment by Wiigian** [comment]
> Min Side. Should I be using the developer one?

Yes, don't ask me how I know

**Comment by phellarv** [comment]
Where do I get the developer API key? I have signed up in the developer portal, but I cannot see any way to get an API key?

**Comment by Wiigian** [comment]
It's listed under products, you have to add a subscription. 
[Take a look at the description here](https://powersaver.no/nodes/ps-elvia-add-tariff.html#description)

**Comment by phellarv** [comment]
> It's listed under products, you have to add a subscription. [Take a look at the description here](https://powersaver.no/nodes/ps-elvia-add-tariff.html#description)

Thanks - Now I'm connected, and all good.
