### ISSUE TITLE
elvia-add-tariff causes node-red to crash

### ISSUE THREAD

**Issue by Wiigian** [ottopaulsen/node-red-contrib-power-saver#76]
I installed the elvia-add-tariff node, and pasted my API key as described in the manual.
After deployment, I received "Unauthorized" from the node, and a minute later, it crashed.

19 Aug 14:23:03 - [red] Uncaught Exception:
19 Aug 14:23:03 - [error] TypeError: Cannot read properties of undefined (reading 'tariffPrice')
    at /config/node-red/node_modules/node-red-contrib-power-saver/src/elvia/elvia-add-tariff.js:31:45
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[14:23:03] WARNING: Node-RED crashed, halting add-on

-----------------------------------------------------------
 Add-on version: 13.3.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.4  (amd64 / qemux86-64)
 Home Assistant Core: 2022.8.6
 Home Assistant Supervisor: 2022.08.3
-----------------------------------------------------------

**Comment by phellarv** [comment]
Same bug as #75 I presume.

**Comment by Wiigian** [comment]
> Same bug as #75 I presume.

Yes, you are right!
