### ISSUE TITLE
Turn on if price is lower in a longer period

### ISSUE THREAD

**Issue by djjoakim** [ottopaulsen/node-red-contrib-power-saver#80]
Hey!
First of all - thanks for this amazing node and work you put behind this.

I have read all the guides and nodes on the site and maybe i am just missing something (?)

I have an water-heater that's controlled by "Lowest-price" node, and set to run max 5hours a day, and not continuous. Sometimes (like tomorrow) the price is low for 10hours that day, i wounder - is it possible somehow to make the heater run more hours that day, when the price is low more then 5hours? I have tried experiencing with best-save node, but i can't get my request to work.

I am pre-heating my water heater so it's no point of having it running more then 5h a day, but if the price is low i would like to have it run more then 5h a day. 
I hope you understand my request and that there maybe already is a solution for this!

Edit:
To explain more simple, add a "Max and Min" setting, so where Max is how many hours to run IF the price is low, and Min is how much it MUST run on 24h, thanks!

Thanks!

**Comment by ottopaulsen** [comment]
That is a good question. You could run 2 Lowest Price nodes in parallell, where you on the other one set it to more hours on, but at the same time use the new config "Max price". However, I am not sure how you can combine these two and get a kind of "OR" between them. Maybe there is a standard node that can be used for that.

Anyway, I will keep this in mind.

**Comment by djjoakim** [comment]
Thanks for the response!
Yes, the "cheap" price is dynamic these days, i solved the problem by adding a node that activates when the price is under 0.30 Öre (SEK) and then check if VVB has run for 5h, if it have, it activates VVB until the price gets over 0.30 Öre again, seems to work pretty good!
Thanks again for you'r awesome nodes, i will make sure to donate.

**Comment by djjoakim** [comment]
Hello again!
After seeing there was an update to "Lowest price" with that Max price option, i will run it that way, and separate them both, seems much smoother! Thanks once again! :)
