### ISSUE TITLE
Possible bug in 3.0.0 - When tomorrows price is not ready node gives error messages

### ISSUE THREAD

**Issue by Swoop86** [ottopaulsen/node-red-contrib-power-saver#9]
See attached image, have not seen it to affect the schedule it creates, but could potentially create issues?
I am assuming this to be because of tomorrows price not being available, will check again after 13:00.

![image](https://user-images.githubusercontent.com/5503114/145783827-cb6535b6-bb9c-4159-ac50-caf747391738.png)

**Comment by Swoop86** [comment]
Errors are gone after 13:00.

**Comment by ottopaulsen** [comment]
Thanks for reporting this.

Could you try again tomorrow before 13.00, and send me the input to the Best Save node? Just put a debug node alongside it and send it the same data.
Also, I would like to see the total output from output 3 on the Best Save node.
A copy of your flow would also be helpful.

Otto

**Comment by Swoop86** [comment]
![Skjermbilde 2021-12-14 kl  12 33 57](https://user-images.githubusercontent.com/5503114/145990806-507b2532-f06a-4eb8-8cd3-2cab4f264987.png)
`#Price receiver
{
   "payload":{
      "priceData":[
         {
            "value":1.633,
            "start":"2021-12-14T00:00:00+01:00"
         },
         {
            "value":1.584,
            "start":"2021-12-14T01:00:00+01:00"
         },
         {
            "value":1.581,
            "start":"2021-12-14T02:00:00+01:00"
         },
         {
            "value":1.583,
            "start":"2021-12-14T03:00:00+01:00"
         },
         {
            "value":1.596,
            "start":"2021-12-14T04:00:00+01:00"
         },
         {
            "value":1.661,
            "start":"2021-12-14T05:00:00+01:00"
         },
         {
            "value":1.746,
            "start":"2021-12-14T06:00:00+01:00"
         },
         {
            "value":2.763,
            "start":"2021-12-14T07:00:00+01:00"
         },
         {
            "value":3.803,
            "start":"2021-12-14T08:00:00+01:00"
         },
         {
            "value":3.921,
            "start":"2021-12-14T09:00:00+01:00"
         },
         {
            "value":3.551,
            "start":"2021-12-14T10:00:00+01:00"
         },
         {
            "value":4.172,
            "start":"2021-12-14T11:00:00+01:00"
         },
         {
            "value":3.683,
            "start":"2021-12-14T12:00:00+01:00"
         },
         {
            "value":3.742,
            "start":"2021-12-14T13:00:00+01:00"
         },
         {
            "value":3.847,
            "start":"2021-12-14T14:00:00+01:00"
         },
         {
            "value":4.315,
            "start":"2021-12-14T15:00:00+01:00"
         },
         {
            "value":4.582,
            "start":"2021-12-14T16:00:00+01:00"
         },
         {
            "value":2.202,
            "start":"2021-12-14T17:00:00+01:00"
         },
         {
            "value":2.153,
            "start":"2021-12-14T18:00:00+01:00"
         },
         {
            "value":1.803,
            "start":"2021-12-14T19:00:00+01:00"
         },
         {
            "value":1.722,
            "start":"2021-12-14T20:00:00+01:00"
         },
         {
            "value":1.716,
            "start":"2021-12-14T21:00:00+01:00"
         },
         {
            "value":1.569,
            "start":"2021-12-14T22:00:00+01:00"
         },
         {
            "value":1.523,
            "start":"2021-12-14T23:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T00:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T01:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T02:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T03:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T04:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T05:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T06:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T07:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T08:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T09:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T10:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T11:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T12:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T13:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T14:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T15:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T16:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T17:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T18:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T19:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T20:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T21:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T22:00:00+01:00"
         },
         {
            "value":null,
            "start":"2021-12-15T23:00:00+01:00"
         }
      ],
      "source":"Nordpool"
   },
   "_msgid":"79e28ebd49fb2425"
}

# Best Save
{
   "payload":{
      "schedule":[
         {
            "time":"2021-12-14T00:00:00+01:00",
            "value":true
         },
         {
            "time":"2021-12-14T07:00:00+01:00",
            "value":false
         },
         {
            "time":"2021-12-15T00:00:00+01:00",
            "value":true
         }
      ],
      "hours":[
         {
            "price":1.633,
            "onOff":true,
            "start":"2021-12-14T00:00:00+01:00",
            "saving":null
         },
         {
            "price":1.584,
            "onOff":true,
            "start":"2021-12-14T01:00:00+01:00",
            "saving":null
         },
         {
            "price":1.581,
            "onOff":true,
            "start":"2021-12-14T02:00:00+01:00",
            "saving":null
         },
         {
            "price":1.583,
            "onOff":true,
            "start":"2021-12-14T03:00:00+01:00",
            "saving":null
         },
         {
            "price":1.596,
            "onOff":true,
            "start":"2021-12-14T04:00:00+01:00",
            "saving":null
         },
         {
            "price":1.661,
            "onOff":true,
            "start":"2021-12-14T05:00:00+01:00",
            "saving":null
         },
         {
            "price":1.746,
            "onOff":true,
            "start":"2021-12-14T06:00:00+01:00",
            "saving":null
         },
         {
            "price":2.763,
            "onOff":false,
            "start":"2021-12-14T07:00:00+01:00",
            "saving":2.763
         },
         {
            "price":3.803,
            "onOff":false,
            "start":"2021-12-14T08:00:00+01:00",
            "saving":3.803
         },
         {
            "price":3.921,
            "onOff":false,
            "start":"2021-12-14T09:00:00+01:00",
            "saving":3.921
         },
         {
            "price":3.551,
            "onOff":false,
            "start":"2021-12-14T10:00:00+01:00",
            "saving":3.551
         },
         {
            "price":4.172,
            "onOff":false,
            "start":"2021-12-14T11:00:00+01:00",
            "saving":4.172
         },
         {
            "price":3.683,
            "onOff":false,
            "start":"2021-12-14T12:00:00+01:00",
            "saving":3.683
         },
         {
            "price":3.742,
            "onOff":false,
            "start":"2021-12-14T13:00:00+01:00",
            "saving":3.742
         },
         {
            "price":3.847,
            "onOff":false,
            "start":"2021-12-14T14:00:00+01:00",
            "saving":3.847
         },
         {
            "price":4.315,
            "onOff":false,
            "start":"2021-12-14T15:00:00+01:00",
            "saving":4.315
         },
         {
            "price":4.582,
            "onOff":false,
            "start":"2021-12-14T16:00:00+01:00",
            "saving":4.582
         },
         {
            "price":2.202,
            "onOff":false,
            "start":"2021-12-14T17:00:00+01:00",
            "saving":2.202
         },
         {
            "price":2.153,
            "onOff":false,
            "start":"2021-12-14T18:00:00+01:00",
            "saving":2.153
         },
         {
            "price":1.803,
            "onOff":false,
            "start":"2021-12-14T19:00:00+01:00",
            "saving":1.803
         },
         {
            "price":1.722,
            "onOff":false,
            "start":"2021-12-14T20:00:00+01:00",
            "saving":1.722
         },
         {
            "price":1.716,
            "onOff":false,
            "start":"2021-12-14T21:00:00+01:00",
            "saving":1.716
         },
         {
            "price":1.569,
            "onOff":false,
            "start":"2021-12-14T22:00:00+01:00",
            "saving":1.569
         },
         {
            "price":1.523,
            "onOff":false,
            "start":"2021-12-14T23:00:00+01:00",
            "saving":1.523
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T00:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T01:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T02:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T03:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T04:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T05:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T06:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T07:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T08:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T09:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T10:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T11:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T12:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T13:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T14:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T15:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T16:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T17:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T18:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T19:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T20:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T21:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T22:00:00+01:00",
            "saving":null
         },
         {
            "price":null,
            "onOff":true,
            "start":"2021-12-15T23:00:00+01:00",
            "saving":null
         }
      ],
      "source":"Nordpool",
      "config":{
         "maxHoursToSaveInSequence":"17",
         "minHoursOnAfterMaxSequenceSaved":"4",
         "minSaving":0.5,
         "sendCurrentValueWhenRescheduling":true,
         "outputIfNoSchedule":true,
         "scheduleOnlyFromCurrentTime":false
      }
   },
   "_msgid":"8fb349d056a6aaa2"
}`

**Comment by Gybrsh** [comment]
Same here. To me, it may seem as if this now only happens at the first execution of the flow ([version 3.0.3](https://ottopaulsen.github.io/node-red-contrib-power-saver/changelog/)). 

Subsequent runs of the flow do not produce the same messages. Restart nodered and it reappears.

**Comment by ottopaulsen** [comment]
Please try the fix in version 3.0.4.
I can see what is going wrong, but I am not 100% sure it is fixed.
If it still isn't working, please send me the input to the Receive Price node, that is the output from the Nordpool sensor.

**Comment by Swoop86** [comment]
Error messages are now gone here.

**Comment by ottopaulsen** [comment]
Great. Closing this, then.
