### ISSUE TITLE
Multiple nodes + manual override in HA

### ISSUE THREAD

**Issue by ozziemannen** [ottopaulsen/node-red-contrib-power-saver#90]
Hello and thanks for creating this!
I'm using Powersaver node for controlling both water heater and a heat pump/inverter.

I've set up the node for the heat pump by splitting each day into 5 "time zones" and using a Lowest Price node for each time zone, like:
- 00.00 - 06.00, On for 3 hpurs
- 06.00 - 10.00, On for 2 h
- 10.00 - 14.00, On for 2 h
- 14.00 - 18.00, On for 2 h
- 18.00 - 00.00, On for 3 h
However, the nodes seem to interfere with each other, so the heat pump doesn't always turn on when it is supposed to.
Maybe my setup is wrong?
<img width="1222" alt="Skärmavbild 2022-10-02 kl  00 20 58" src="https://user-images.githubusercontent.com/62818090/193430666-116e2adb-4e4a-4438-95d9-fd257e295957.png">

The other question (or request) is for a possibility to manually edit an automated schedule, from within Home Assistant I guess.
Like maybe have a switch for each hour of the day, that individually get set to on/off when the new price from Nordpool is fetched, and then you could change those switches manually if you'd want . Any thoughts about this?

**Comment by ozziemannen** [comment]
And the visualization:
<img width="688" alt="Skärmavbild 2022-10-02 kl  00 37 42" src="https://user-images.githubusercontent.com/62818090/193430804-09414ae3-213f-4967-aea5-e33cdf18ea72.png">

**Comment by marhoy** [comment]
@ozziemannen See also my response [here](https://github.com/ottopaulsen/node-red-contrib-power-saver/issues/92#issuecomment-1266940527) on how I handle output from multiple schedulers running in parallell.

**Comment by ozziemannen** [comment]
Thanks! I'll give it a try.

**Comment by ottopaulsen** [comment]
You should try the new Schedule Merger node to merge all the Lowest Price schedules into one.
Also take a look at the Fixed Schedule node.

**Comment by ozziemannen** [comment]
> You should try the new Schedule Merger node to merge all the Lowest Price schedules into one. Also take a look at the Fixed Schedule node.

Thanks! Seems to be working fine:)
