### ISSUE TITLE
Fills the debug log in seconds.

### ISSUE THREAD

**Issue by Mheel80** [ottopaulsen/node-red-contrib-power-saver#91]
Hello.
The lowest price node fills the debug log in a few seconds making it inpossible to use the debug logg.
![received_1004267500970814](https://user-images.githubusercontent.com/61874697/193445331-4794f1dd-779c-4f89-91c8-f25c12e7b757.jpeg)

**Comment by ottopaulsen** [comment]
Check how often you send data in to the node. I believe this output cones only once for each time it receives data.

**Comment by Mheel80** [comment]
I inject it every second. That because if i change any values i want it to apply instantly.

**Comment by marhoy** [comment]
@Mheel80 Trigger on events from HA instead. No need to re-send the input if nothing changed.

**Comment by Mheel80** [comment]
@marhoy I have changed so It doesnt inject every second and It works if I have a schedule but when It says no schedule It keeps sending no schedule every second in the logg.

**Comment by ottopaulsen** [comment]
Please verify that the node does not also get input every second. I cannot imagine anything in there sending the message every second unless it gets input.

**Comment by Mheel80** [comment]
@ottopaulsen Yes that is the problem and if i change them to state nodes the flow will not work until all have changed value. I will try to figure out a solution.

**Comment by marhoy** [comment]
@Mheel80 If you explain what you want to achieve, maybe we can suggest a useful flow?

**Comment by Mheel80** [comment]
@marhoy Sure. I have set up the following so it can be changed from the dashboard in HA. 
![image](https://user-images.githubusercontent.com/61874697/194010821-bc1c1f06-b940-4311-aa94-f29064950dcf.png)
If i use state node and I modify the flow and do a modifyed deployment it will not send the values to the next node in node red untill it changes value. This results to that the lowest price node cant plan a schedule because it doesnt have the correct values.  I will have the same problem if i restart HA or my server restarts.
Here I have restarted HA and used state nodes. 
![image](https://user-images.githubusercontent.com/61874697/194011919-27f6eb25-258a-4e62-8736-7814620c0d23.png)
This is how it looks when i have changed all values after restart.
![image](https://user-images.githubusercontent.com/61874697/194012300-47999b69-0d4a-4ca1-a1e8-7c0e44cd4b82.png)

**Comment by marhoy** [comment]
@Mheel80 What is it that you are trying to do?
You have a spa bath, and you want to control what property of it in what way?

**Comment by Mheel80** [comment]
@marhoy I change the temperture setpoints depending on the price. All that works.

**Comment by Mheel80** [comment]
@marhoy I trying the following and it looks like it is working.
![image](https://user-images.githubusercontent.com/61874697/194038774-2ecd21b3-9602-4f9b-83a4-f151fa63b03a.png)

**Comment by ottopaulsen** [comment]
Is this still an issue?
If not, please close.
