### ISSUE TITLE
Suggestion: Template for visualizing heat capacitor

### ISSUE THREAD

**Issue by niklasgisselman** [ottopaulsen/node-red-contrib-power-saver#99]
I just love the Lovelace visualization of the on/off of the water heater. It would be great to have a similar visualization of the heat capacitor, to be able to see how the temperature will be set during different prices. 

![image](https://user-images.githubusercontent.com/69214338/195194578-6e9374db-9089-4070-a94b-604161a4a285.png)

**Comment by phellarv** [comment]
Here is an example on how to visualize it.
Node Red Flow: https://pastebin.com/xdtV1fHy
Apex Chart: https://pastebin.com/WmdPXwgH

**Comment by niklasgisselman** [comment]
Great! Thanks alot!
